project:
  type: website

website:
  title: "ISSS626 - Geospatial"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
        - href: "Hands-on_Ex/Hands_on_ex01.html"
          text: "Hands-on Exercise 1A"

    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - minty
    css: styles.css
    toc: true

editor: visual