{
  "hash": "831d98d607db9f3aefa8bd9c9814ff11",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Hands-on Exercise 5A\"\nauthor: \"Chong Jia Min Heidi\"\nformat: html\ndate: \"September 23 2026\"\ndate-modified: \"last-modified\"\nexecute:\n  echo: true \n  eval: true \n  warning: false \n  freeze: true\n  message: false\n---\n\n# Overview\n\nIn spatial policy, one of the main development objective of the local government and planners is to ensure equal distribution of development in the province. Therefore in this study, it is imperative to know how to apply appropriate spatial statistical methods to discover if development are even distributed geographically.\n\nIf the answer is **No**. Then, our next question will be “is there sign of spatial clustering?”.\n\nAnd, if the answer for this question is yes, then our next question will be “where are these clusters?\n\nWe will be computing Global Measures of Spatial Autocorrelation (GMSA), through the use of the **spdep** package.\n\n# Getting Started\n\n## Importing of Data\n\nThese packages will be used.\n\n- **sf** is use for importing and handling geospatial data in R,\n\n- **tidyverse** is mainly use for wrangling attribute data in R,\n\n- **spdep** will be used to compute spatial weights, global and local spatial autocorrelation statistics\n\n- **tmap** will be used to prepare cartographic quality chropleth map.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, spdep, tmap, tidyverse,knitr,kableExtra)\n```\n:::\n\n\nWe will be using the Hunan data from the In-class exercise 4. The below will be done for importing the data\n\n- import the Hunan shapefile and parse it into a sf polygon feature object\n\n- Import Hunan_2012.csv file and parse it into a tibble data.frame\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Hunan county boundary layer\nhunan <- st_read(\"data/geospatial/hunan/Hunan.shp\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Hunan' from data source \n  `C:\\cjmheidii\\ISSS626 - Geospatial\\Hands-on_Ex\\data\\geospatial\\hunan\\Hunan.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 88 features and 7 fields\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: 108.7831 ymin: 24.6342 xmax: 114.2544 ymax: 30.12812\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\n#This is the csv Hunan local development indicators \n#This will be in the  R dataframe class\nhunan_2012<- read_csv(\"data/aspatial/Hunan_2012.csv\")\n```\n:::\n\n\n## Data joining\n\nNow the relational join is conducted and the required data columns are retained (the unnecessary data columns are removed to not waste memory and space!)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan <- left_join(hunan,hunan_2012) %>%\n  select(1:4, 7, 15)\n```\n:::\n\n\n## Data Plotting\n\nFinally a basemap and a choropleth map showing the distribution of GDPPC 2012 by using `qtm()` of **tmap** package will be plotted out for initial reading.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Hands-on_ex05A_files/figure-html/unnamed-chunk-4-1.png){width=1536}\n:::\n:::\n\n\n::: callout-note\nThe steps conducted here are similar to that we had done in In-Class exercise 4. Do take note of the things learnt before like :\n\n- Joining of 2 files (Plus types of joins)\n\n- Plot sizing when plotting out using tmap packages\n\n- The legend and layout (how to manipulate it to ensure data is properly shown and not be covered)\n:::\n\n# Global Measures of Spatial Autocorrelation\n\n## Using the QUEEN Neighbour argument\n\nBefore the global spatial autocorrelation statistics can be computed, a spatial weights of the study area has to be conducted (recap from Hands on 4). The spatial weights is used to define the neighbourhood relationships between the geographical units (i.e. county) in the study area.\n\nIn the code chunk below, [`poly2nb()`](https://r-spatial.github.io/spdep/reference/poly2nb.html) of **spdep** package is used to compute contiguity weight matrices for the study area.\n\nThis function builds a neighbours list based on regions with contiguous boundaries. Recall the use of the QUEEN argument that takes TRUE or FALSE as options. If you do not specify this argument the default is set to TRUE, that is, if you don’t specify queen = FALSE this function will return a list of first order neighbours using the Queen criteria.\n\nFor recalling, the table from Hands on 4 is put in to look again at the QUEEN argument in finding neighbours as compared to the QUEEN Counterpart arguments.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#| echo: false\nlibrary(knitr)\n\ndf <- data.frame(\n  Situation = c(\"Share a full edge\",\n                \"Share only a single corner point\",\n                \"Share nothing\",\n                \"Touch at a single point (diagonal)\"),\n  `Rook Neighbour` = c(\"✅\", \"❌\", \"❌\", \"❌\"),\n  `Queen Neighbour` = c(\"✅\", \"✅\", \"❌\", \"✅\"),\n  check.names = FALSE\n)\n\nkable(df)\n```\n\n::: {.cell-output-display}\n\n\n|Situation                          |Rook Neighbour |Queen Neighbour |\n|:----------------------------------|:--------------|:---------------|\n|Share a full edge                  |✅             |✅              |\n|Share only a single corner point   |❌             |✅              |\n|Share nothing                      |❌             |❌              |\n|Touch at a single point (diagonal) |❌             |✅              |\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_q <- poly2nb(hunan, \n                queen=TRUE)\nsummary(wm_q)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 448 \nPercentage nonzero weights: 5.785124 \nAverage number of links: 5.090909 \nLink number distribution:\n\n 1  2  3  4  5  6  7  8  9 11 \n 2  2 12 16 24 14 11  4  2  1 \n2 least connected regions:\n30 65 with 1 link\n1 most connected region:\n85 with 11 links\n```\n\n\n:::\n:::\n\n\n::: callout-note\nThis to recall means that within the 88 regions there are 448 non-0 links.\n\nThe most connected area unit has 11 neighbours (there is only unit with 11 neighbours which is region 85). There are two area units with only one neighbours and these are regions 30 and 65. Where the average number of links will also be 5.090909 (where mode of number of links is also 5 as seen from the distribution \"table\".\n:::\n\n## Assigning Weights\n\nNext, we need to assign weights to each neighboring polygon. In our case, each neighboring polygon will be assigned equal weight (style=“W”).\n\nThis is accomplished by assigning the fraction 1/(#ofneighbors) to each neighboring county then summing the weighted income values.\n\n::: callout-caution\nTAKE NOTE : it has one drawback in that polygons along the edges of the study area will base their lagged values on fewer polygons thus potentially over- or under-estimating the true nature of the spatial autocorrelation in the data.\n:::\n\nWe’ll stick with the style=“W” option for simplicity’s sake in this case but note that other more robust options are available, notably style=“B”.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrswm_q <- nb2listw(wm_q, \n                   style=\"W\", \n                   zero.policy = TRUE)\nrswm_q\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCharacteristics of weights list object:\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 448 \nPercentage nonzero weights: 5.785124 \nAverage number of links: 5.090909 \n\nWeights style: W \nWeights constants summary:\n   n   nn S0       S1       S2\nW 88 7744 88 37.86334 365.9147\n```\n\n\n:::\n:::\n\n\n::: callout-note\nTake note!\n\n- The input of [`nb2listw()`](https://r-spatial.github.io/spdep/reference/nb2listw.html) must be an object of class **nb**. The syntax of the function has two major arguments, namely style and zero.poly.\n\n- *style* can take values “W”, “B”, “C”, “U”, “minmax” and “S”. B is the basic binary coding, W is row standardised (sums over all links to n), C is globally standardised (sums over all links to n), U is equal to C divided by the number of neighbours (sums over all links to unity), while S is the variance-stabilizing coding scheme proposed by Tiefelsdorf et al. 1999, p. 167-168 (sums over all links to n).\n\n- If *zero policy* is set to TRUE, weights vectors of zero length are inserted for regions without neighbour in the neighbours list. These will in turn generate lag values of zero, equivalent to the sum of products of the zero row t(rep(0, length=length(neighbours))) %\\*% x, for arbitrary numerical vector x of length length(neighbours). The spatially lagged value of x for the zero-neighbour region will then be zero, which may (or may not) be a sensible choice.\n:::\n\n# Global Measures of Spatial Autocorrelation : Moran's I\n\nAs an introduction, **Moran's I** tells you if nearby locations tend to have similar values (positive autocorrelation), dissimilar values (negative autocorrelation), or are randomly arranged (no autocorrelation).\n\nBasically, it says if it correlates a variable with itself across space. Below is a table to summarise the basic gist of details.\n\n## Moran's I Test\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover table-condensed\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Interpretation of Moran's I</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Moran's I </th>\n   <th style=\"text-align:left;\"> Pattern </th>\n   <th style=\"text-align:left;\"> Meaning </th>\n   <th style=\"text-align:left;\"> Example </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> +ve (I &gt; 0) </td>\n   <td style=\"text-align:left;\"> Clustered </td>\n   <td style=\"text-align:left;\"> Similar values attract — spatial clustering </td>\n   <td style=\"text-align:left;\"> Wealthy neighborhoods clustered together </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> -ve (I &lt; 0) </td>\n   <td style=\"text-align:left;\"> Dispersed </td>\n   <td style=\"text-align:left;\"> Dissimilar values repel — spatial dispersion </td>\n   <td style=\"text-align:left;\"> Alternating rich / poor blocks </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> ≈ 0 </td>\n   <td style=\"text-align:left;\"> Random </td>\n   <td style=\"text-align:left;\"> No spatial autocorrelation </td>\n   <td style=\"text-align:left;\"> No discernible spatial structure </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmoran.test(hunan$GDPPC, \n           listw=rswm_q, \n           zero.policy = TRUE, \n           na.action=na.omit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  hunan$GDPPC  \nweights: rswm_q    \n\nMoran I statistic standard deviate = 4.7351, p-value = 1.095e-06\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.300749970      -0.011494253       0.004348351 \n```\n\n\n:::\n:::\n\n\n::: callout-note\nanalysis :\n\nWith the p value≈ 1.1 × 10⁻⁶ \\< 0.001, we can reject H0 on the point on Spatial Randomness in Hunan. Through the observed I being 0.3 and the expected I being -0.011 (if its randomised). It can be noted that Hunan is strongly spatially concentrated (0.3-0.5 Observed I value for it to be strong)\n\nTherefore the counties in Hunan with a high GDP per capita tend to be located near other high GDP areas and low GDP areas tend to be near to other low GDP areas as well. Spatially, those with similar wealth amounts are concentrated.\n:::\n\n## Computing Monte Carlo Moran's I\n\nTo introduce the process :\n\nMonte Carlo **empirically builds the null distribution** by brute force:\n\n1.  Take the GDP values (in this scenario).\n\n2.  **Randomly shuffle** them across the map (breaking any spatial structure).\n\n3.  Recompute Moran's I on the shuffled data.\n\n4.  Repeat **n**(depending on what nsim is set to).\n\n5.  Compare your **actual** observed I to the n shuffled values.\n\nThis gives you a **reference distribution** of \"what I looks like when there's no spatial pattern.\n\n::: callout-note\nRemember the set seed? When we are doing a Monte Carlo it is compulsory to put a set seed to ensure the values that are calculated will always stay the same (or if re-run the Moran's I value will change again! which will cause trouble when using the values for analysis)\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nbperm= moran.mc(hunan$GDPPC, \n                listw=rswm_q, \n                nsim=999, \n                zero.policy = TRUE, \n                na.action=na.omit)\nbperm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  hunan$GDPPC \nweights: rswm_q  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.30075, observed rank = 1000, p-value = 0.001\nalternative hypothesis: greater\n```\n\n\n:::\n:::\n\n\n::: callout-note\nAnalysis:\n\nWith a p value =0.001 \\<0.05 we can again reject the H0 that Hunan is spatially randomly distributed. (H1 being the fact that the Hunan counties are actually spatially concentrated based on wealth).\n\nAlso with the observed rank of 1000 (over 1000), it also proves that Hunan GDP map is more spatially clustered than essentially every random rearrangement\n:::\n\n## Visualising Moran's I\n\nIt is always a good practice for us the examine the simulated Moran’s I test statistics in greater detail. This can be achieved by plotting the distribution of the statistical values as a histogram by using the code chunk below.\n\nIn the code chunk below [`hist()`](https://www.rdocumentation.org/packages/graphics/versions/3.6.2/topics/hist) and [`abline()`](https://www.rdocumentation.org/packages/graphics/versions/3.6.2/topics/abline) of R Graphics are used.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.01504572\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvar(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.004371574\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n-0.18339 -0.06168 -0.02125 -0.01505  0.02611  0.27593 \n```\n\n\n:::\n:::\n\n\nNow with the brief summary statistics we plot out the Morans I\n\n### Base Graph Plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(bperm$res, \n     freq=TRUE, \n     breaks=20, \n     xlab=\"Simulated Moran's I\")\nabline(v=0, \n       col=\"red\") \n```\n\n::: {.cell-output-display}\n![](Hands-on_ex05A_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n::: callout-note\nAnalysis :\n\nThe simulated values cluster around the theoretical expectation of −0.011 (red line marks 0), with most mass between −0.15 and +0.15. The observed Moran's I (0.301) lies entirely outside the simulated range, confirming strong positive spatial autocorrelation and rejecting the null hypothesis of spatial randomness (p = 0.001).\n:::\n\n### GGplot plot\n\nThe alternative is to plot using ggplot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data.frame(I = bperm$res), aes(x = I)) +\n  geom_histogram(bins = 20, fill = \"steelblue\", color = \"white\") +\n  geom_vline(xintercept = 0, color = \"red\", linewidth = 1) +\n  labs(\n    x = \"Simulated Moran's I\",\n    y = \"Frequency\",\n    title = \"Monte Carlo Simulation of Moran's I\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Hands-on_ex05A_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n# Global Measures of Spatial Autocorrelation: Geary's C\n\n## Geary's C test\n\nGeary C tells you whether nearby locations have similar or dissimilar values. But it's built differently, and that difference matters.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- data.frame(\n  `Geary's C` = c(\"C ≈ 0\", \"0 < C < 1\", \"C ≈ 1\", \"1 < C < 2\", \"C ≈ 2\", \"C > 2\"),\n  Pattern     = c(\"Strong clustering\", \"Clustering\", \"Random\", \"Dispersion\", \"Strong dispersion\", \"Extreme dispersion\"),\n  Meaning     = c(\n    \"Neighbours are nearly identical\",\n    \"Neighbours are more similar than random\",\n    \"No spatial autocorrelation\",\n    \"Neighbours are more different than random\",\n    \"Perfect checkerboard pattern\",\n    \"Highly dissimilar neighbours\"\n  ),\n  Example     = c(\n    \"Adjacent areas share almost the same value\",\n    \"High values near high values, low near low\",\n    \"Values arranged with no spatial structure\",\n    \"High values surrounded by low values\",\n    \"Strict alternation high–low–high–low\",\n    \"Extreme contrast between adjacent areas\"\n  ),\n  check.names = FALSE\n)\n\nkable(df, caption = \"Interpretation of Geary's C\") |>\n  kable_styling(\n    bootstrap_options = c(\"striped\", \"hover\", \"condensed\"),\n    full_width = FALSE,\n    position = \"center\"\n  )\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover table-condensed\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Interpretation of Geary's C</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Geary's C </th>\n   <th style=\"text-align:left;\"> Pattern </th>\n   <th style=\"text-align:left;\"> Meaning </th>\n   <th style=\"text-align:left;\"> Example </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> C ≈ 0 </td>\n   <td style=\"text-align:left;\"> Strong clustering </td>\n   <td style=\"text-align:left;\"> Neighbours are nearly identical </td>\n   <td style=\"text-align:left;\"> Adjacent areas share almost the same value </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 0 &lt; C &lt; 1 </td>\n   <td style=\"text-align:left;\"> Clustering </td>\n   <td style=\"text-align:left;\"> Neighbours are more similar than random </td>\n   <td style=\"text-align:left;\"> High values near high values, low near low </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> C ≈ 1 </td>\n   <td style=\"text-align:left;\"> Random </td>\n   <td style=\"text-align:left;\"> No spatial autocorrelation </td>\n   <td style=\"text-align:left;\"> Values arranged with no spatial structure </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 1 &lt; C &lt; 2 </td>\n   <td style=\"text-align:left;\"> Dispersion </td>\n   <td style=\"text-align:left;\"> Neighbours are more different than random </td>\n   <td style=\"text-align:left;\"> High values surrounded by low values </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> C ≈ 2 </td>\n   <td style=\"text-align:left;\"> Strong dispersion </td>\n   <td style=\"text-align:left;\"> Perfect checkerboard pattern </td>\n   <td style=\"text-align:left;\"> Strict alternation high–low–high–low </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> C &gt; 2 </td>\n   <td style=\"text-align:left;\"> Extreme dispersion </td>\n   <td style=\"text-align:left;\"> Highly dissimilar neighbours </td>\n   <td style=\"text-align:left;\"> Extreme contrast between adjacent areas </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngeary.test(hunan$GDPPC, listw=rswm_q)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tGeary C test under randomisation\n\ndata:  hunan$GDPPC \nweights: rswm_q   \n\nGeary C statistic standard deviate = 3.6108, p-value = 0.0001526\nalternative hypothesis: Expectation greater than statistic\nsample estimates:\nGeary C statistic       Expectation          Variance \n        0.6907223         1.0000000         0.0073364 \n```\n\n\n:::\n:::\n\n\n::: callout-note\nAnalysis:\n\nFirst, with p =0.0001526\\<0.001, it is highly significant and we reject H0 where Hunan is plotted with spatial randomness. This is further supposed by the standard deviate =3.6108 where the observed C is 3.6 SDs below expectation, which is again strong evidence against randomness in Hunan. With C=0.6907 \\<1, it shows that the neighbours are more similar than random and the presence of positive spatial autocorrelation (clustering).\n\nTherefore in conclusion there is statistically significant positive spatial autocorrelation in GDP per capita across Hunan where through the Geary C score, Z score and P it confirms that the evidence against randomness is not by chance. It means basically that counties with similar GDP per capita tend to be spatially adjacent — high-GDP counties cluster together, and low-GDP counties cluster together\n:::\n\n## Computing Monte Carlo Geary C\n\nConcept is similar to Moran's test on Monte Carlo, except we are using the Geary C instead.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nbperm=geary.mc(hunan$GDPPC, \n               listw=rswm_q, \n               nsim=999)\nbperm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Geary C\n\ndata:  hunan$GDPPC \nweights: rswm_q  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.69072, observed rank = 1, p-value = 0.001\nalternative hypothesis: greater\n```\n\n\n:::\n:::\n\n\n::: callout-note\nWith a p value =0.001 \\<0.05 we can again reject the H0 that Hunan is spatially randomly distributed. (H1 being the fact that the Hunan counties are actually spatially concentrated based on wealth).\n\nAlso with the observed rank of 1, The observed C here is ranked lowest of all 1000 values here. This show extreme clustering, where the Hunan GDP map is more spatially clustered than essentially every random rearrangement.\n\n(As a note, a rank of 1 here in the Geary Monte Carlo C is also the strongest possible clustering signal the test can produce)\n:::\n\n## Visualising the Monte Carlo Geary's C\n\nSimilar to the Moran's test before, the histogram is plotted out\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.004402\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvar(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.007436493\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n 0.7142  0.9502  1.0052  1.0044  1.0595  1.2722 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(bperm$res, freq=TRUE, breaks=20, xlab=\"Simulated Geary c\")\nabline(v=1, col=\"red\") \n```\n\n::: {.cell-output-display}\n![](Hands-on_ex05A_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n::: callout-note\nAnalysis :\n\nThe Monte Carlo null distribution of Geary's C for Hunan GDP per capita (999 permutations). Simulated values centre on the theoretical expectation of C = 1.0 (red line), with most mass between 0.85 and 1.2. The observed Geary's C (0.691) lies entirely outside the simulated range on the low side, confirming strong positive spatial autocorrelation (clustering) and rejecting the null hypothesis of spatial randomness (p = 0.001)\n:::\n\n# Spatial Correlogram\n\nSpatial correlograms are great to examine patterns of spatial autocorrelation in your data or model residuals.\n\nThey show how correlated are pairs of spatial observations when you increase the distance (lag) between them - they are plots of some index of autocorrelation (Moran’s I or Geary’s c) against distance.\n\nAlthough correlograms are not as fundamental as variograms (a keystone concept of geostatistics), they are very useful as an exploratory and descriptive tool. For this purpose they actually provide richer information than variograms.\n\n## Compute Moran's I correlogram\n\nIn the code chunk below, [`sp.correlogram()`](https://r-spatial.github.io/spdep/reference/sp.correlogram.html) of **spdep** package is used to compute a 6-lag spatial correlogram of GDPPC. The global spatial autocorrelation used in Moran’s I. The **plot()** of base Graph is then used to plot the output.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nMI_corr <- sp.correlogram(wm_q, \n                          hunan$GDPPC, \n                          order=6, \n                          method=\"I\", \n                          style=\"W\")\nplot(MI_corr)\n```\n\n::: {.cell-output-display}\n![](Hands-on_ex05A_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\nBy plotting the output might not allow us to provide complete interpretation. This is because not all autocorrelation values are statistically significant. Hence, it is important for us to examine the full analysis report by printing out the analysis results as in the code chunk below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(MI_corr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatial correlogram for hunan$GDPPC \nmethod: Moran's I\n         estimate expectation   variance standard deviate Pr(I) two sided    \n1 (88)  0.3007500  -0.0114943  0.0043484           4.7351       2.189e-06 ***\n2 (88)  0.2060084  -0.0114943  0.0020962           4.7505       2.029e-06 ***\n3 (88)  0.0668273  -0.0114943  0.0014602           2.0496        0.040400 *  \n4 (88)  0.0299470  -0.0114943  0.0011717           1.2107        0.226015    \n5 (88) -0.1530471  -0.0114943  0.0012440          -4.0134       5.984e-05 ***\n6 (88) -0.1187070  -0.0114943  0.0016791          -2.6164        0.008886 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n::: callout-note\nAnalysis :\n\nWith Moran's I falling monotonically from lag 1 to lag 4, it shows that the clustering decays smoothly with distance.Where from lag 5 onwards the Moran's I =-0.153 (first negative value), so it shows that there is dispersion.\n\nTherefore it suggests a local spatial dependence on GDP per capita since the spatial dependence has decayed to insignificance within roughly three neighbour orders.\n:::\n\n## Geary C Correlogram\n\nIn the code chunk below, `sp.correlogram()` of **spdep** package is used to compute a 6-lag spatial correlogram of GDPPC. The global spatial autocorrelation used in Geary’s C. The **plot()** of base Graph is then used to plot the output.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nGC_corr <- sp.correlogram(wm_q, \n                          hunan$GDPPC, \n                          order=6, \n                          method=\"C\", \n                          style=\"W\")\nplot(GC_corr)\n```\n\n::: {.cell-output-display}\n![](Hands-on_ex05A_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(GC_corr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatial correlogram for hunan$GDPPC \nmethod: Geary's C\n        estimate expectation  variance standard deviate Pr(I) two sided    \n1 (88) 0.6907223   1.0000000 0.0073364          -3.6108       0.0003052 ***\n2 (88) 0.7630197   1.0000000 0.0049126          -3.3811       0.0007220 ***\n3 (88) 0.9397299   1.0000000 0.0049005          -0.8610       0.3892612    \n4 (88) 1.0098462   1.0000000 0.0039631           0.1564       0.8757128    \n5 (88) 1.2008204   1.0000000 0.0035568           3.3673       0.0007592 ***\n6 (88) 1.0773386   1.0000000 0.0058042           1.0151       0.3100407    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "Hands-on_ex05A_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}