{
  "hash": "9395f8fe122d6b05635dca56582c873a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-Home Exercise 1\"\nauthor: \"Chong Jia Min Heidi\"\nformat: html\ndate: \"September 12 2026\"\ndate-modified: \"last-modified\"\nexecute:\n  echo: true \n  eval: true \n  warning: false \n  freeze: true\n  message: false\n---\n\n# Overview\n\nPublic safety refers to the protection of the general public, communities, and critical infrastructure from crimes, disasters, accidents, and other major threats through coordinated government and agency action.\n\nGeospatial analytics, supported by multi-source geospatial data and geospatial data science and analysis methods, provides powerful means to transform location-based data into visual evidence, analytical insights, and decision support. It plays an important role in areas such as law enforcement, emergency management, disaster response, transportation safety, and environmental management.\n\nA spatial point pattern represents a collection of geographic locations at which particular events occur, such as forest-fire detections or road traffic accidents. A spatio-temporal point pattern extends this representation by incorporating the time at which each event occurs, allowing analysts to investigate how the distribution and interaction of events vary across both space and time.\n\nUnderstanding where and when public-safety events occur can help planners and managers identify areas of concern, understand patterns of event occurrence, allocate resources, and develop evidence-informed strategies for prevention and response.\n\n## Objectives\n\nThis take-home exercise investigates the spatial and/or spatio-temporal patterns of public-safety point events using one the case study of **Road traffic accidents** within the Thailand with emphasis on the Bangkok Metropolitan Region (BMR) for the selected study year 2022.\n\nIn Thailand, it is known that they have recorded one of the [highest road death tolls in the world](https://www.nationthailand.com/in-focus/40010768), which emphasizes the importance of having this analysis within the exercise to gain proper insights to help make better decisions and actionable(s) to reduce the accident rates in the country and in lieu the death toll.\n\nThe specific objectives from this exercise are :\n\n- To prepare and integrate real-world geospatial and temporal data for spatial and spatio-temporal point-pattern analysis.\n\n- To investigate first-order properties of the point pattern by examining how the intensity or distribution of events varies across space and/or time.\n\n- To investigate second-order properties by examining whether events exhibit evidence of spatial or spatio-temporal interaction, such as clustering, inhibition, or approximate randomness.\n\n- To critically evaluate the analytical assumptions, methodological choices, and limitations associated with the selected point-pattern methods.\n\n- To communicate the analytical findings effectively through appropriate geovisualisation and geocommunication.\n\n- To translate the analytical evidence into meaningful implications for public-safety planning and management.\n\n# Data\n\nThese are the datasets used for the exercise\n\n## Thailand Road Accident Dataset\n\n<https://www.kaggle.com/datasets/thaweewatboy/thailand-road-accident-2019-2022>\n\nThis is a comprehensive dataset on recorded road accidents in Thailand, spanning from approximately 2019 to 2022. For the sake of the exercise only the latest data of 2022 will be used here.\n\n::: callout-note\nThe data is from the Office of the Permanent Secretary, Ministry of Transport, where for easier visualisation the [public dashboard](https://trams.mot.go.th/main-dashboard) can be accessed as well.\n:::\n\n## Thailand Boundary Map\n\n<https://www.geoboundaries.org/countryDownloads.html>\n\nThis is the Thailand Boundary map published by the Royal Thai Survey Department, OCHA ROAP on the [geoBoundaries](https://www.geoboundaries.org/) website in 2019 (This is also the latest version available for public download).\n\n# Task 1: Getting Started - Preparation of Data\n\n::: {.callout-important style=\"color:red\"}\nWhen explaining the code, explanations for the code itself when necessary are within the R code comment and not the usual prose text! This is to make the explanations easier to understand as it is added right before the code itself!!\n:::\n\n## Importing of data\n\nFirst the required libraries are installed/loaded into file.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, spatstat, sparr, stpp, tmap, tidyverse, lubridate,gt)\n```\n:::\n\n\nNow we load in both datasets.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Thailand Road Accident Dataset\nacc<- read_csv(\"data/aspatial/thai_road_accident_2019_2022.csv\")\n```\n:::\n\n\nHere we will check the summary of the **Thailand Road Accident** Dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(acc) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 18\n  acc_code incident_datetime   report_datetime     province_th province_en      \n     <dbl> <dttm>              <dttm>              <chr>       <chr>            \n1   571905 2019-01-01 00:00:00 2019-01-02 06:11:00 ลพบุรี        Loburi           \n2  3790870 2019-01-01 00:03:00 2020-02-20 13:48:00 อุบลราชธานี   Ubon Ratchathani \n3   599075 2019-01-01 00:05:00 2019-01-01 10:35:00 ประจวบคีรีขันธ์ Prachuap Khiri K…\n4   571924 2019-01-01 00:20:00 2019-01-02 05:12:00 เชียงใหม่     Chiang Mai       \n5   599523 2019-01-01 00:25:00 2019-01-04 09:42:00 นครสวรรค์    Nakhon Sawan     \n6   571982 2019-01-01 00:30:00 2019-01-07 12:46:00 แม่ฮ่องสอน    Mae Hong Son     \n# ℹ 13 more variables: agency <chr>, route <chr>, vehicle_type <chr>,\n#   presumed_cause <chr>, accident_type <chr>,\n#   number_of_vehicles_involved <dbl>, number_of_fatalities <dbl>,\n#   number_of_injuries <dbl>, weather_condition <chr>, latitude <dbl>,\n#   longitude <dbl>, road_description <chr>, slope_description <chr>\n```\n\n\n:::\n:::\n\n\nNow we will load in the second dataset : Thailand Boundary Map.\n\nWe will look into detail on the datasets after loading it in, in the next subsection.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Thailand Boundary Map\nthai_map <- st_read(\"data/geospatial/Thai/geoBoundaries-THA-ADM2.shp\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `geoBoundaries-THA-ADM2' from data source \n  `C:\\cjmheidii\\ISSS626 - Geospatial\\Hands-on_Ex\\data\\geospatial\\Thai\\geoBoundaries-THA-ADM2.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 928 features and 5 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 97.34336 ymin: 5.613038 xmax: 105.637 ymax: 20.46507\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\n# Column names\nnames(thai_map)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"shapeName\"  \"shapeISO\"   \"shapeID\"    \"shapeGroup\" \"shapeType\" \n[6] \"geometry\"  \n```\n\n\n:::\n\n```{.r .cell-code}\n# Preview attributes without geometry\nst_drop_geometry(thai_map) %>% head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       shapeName shapeISO                 shapeID shapeGroup shapeType\n1    Akat Amnuai     <NA> 78962969B83463915016953        THA      ADM2\n2        Amphawa     <NA> 78962969B68169586280131        THA      ADM2\n3        Ao Luek     <NA> 78962969B54777225393770        THA      ADM2\n4  Aranyaprathet     <NA> 78962969B18658138340114        THA      ADM2\n5       At Samat     <NA> 78962969B71289419444255        THA      ADM2\n6          Bacho     <NA> 78962969B22586560209583        THA      ADM2\n7  Bamnet Narong     <NA> 78962969B89125519314325        THA      ADM2\n8      Ban Bueng     <NA> 78962969B10446742029293        THA      ADM2\n9      Ban Chang     <NA> 78962969B38445835691017        THA      ADM2\n10       Ban Dan     <NA> 78962969B34946496747939        THA      ADM2\n```\n\n\n:::\n\n```{.r .cell-code}\nst_drop_geometry(thai_map) %>% glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 928\nColumns: 5\n$ shapeName  <chr> \"Akat Amnuai\", \"Amphawa\", \"Ao Luek\", \"Aranyaprathet\", \"At S…\n$ shapeISO   <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ shapeID    <chr> \"78962969B83463915016953\", \"78962969B68169586280131\", \"7896…\n$ shapeGroup <chr> \"THA\", \"THA\", \"THA\", \"THA\", \"THA\", \"THA\", \"THA\", \"THA\", \"TH…\n$ shapeType  <chr> \"ADM2\", \"ADM2\", \"ADM2\", \"ADM2\", \"ADM2\", \"ADM2\", \"ADM2\", \"AD…\n```\n\n\n:::\n\n```{.r .cell-code}\n# How many unique values per column\nst_drop_geometry(thai_map) %>% summarise(across(everything(), n_distinct))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  shapeName shapeISO shapeID shapeGroup shapeType\n1       918        1     928          1         1\n```\n\n\n:::\n:::\n\n\n## Data Inspection & Cleaning.\n\nA Point event is basically defined as a single record within the dataset, or a specific road traffic accident Each event will be geolocated using the `longitude` and `latitude` columns.\n\nSo it is important that any duplicated rows of data do not exist and we handle all missing or invalid coordinates, which will be done in this sub-section.\n\nSeveral things will checked upon within this subsection. These include\n\n- Handling of Invalid/Missing Locations\n\n- Removal of Unnecessary Columns & rows\n\n- Ensuring Unique Rows\n\n### Handling Invalid/Missing Locations\n\nFirst, to ensure there is no invalid rows (error due to location column issues, we will check for rows with unknown or NA provinces).\n\nThis is important since during analysis when writing out the insights, we will link back to the province column rather than the latitude and longitutde column for readers to understand better. The latitude and longitude gives the specific point of the accident but with just these 2 columns readers dont know which city or province we are going to talk about.\n\n::: callout-note\nIf there are any unknown province locations, check for unknown latitude and longitude. To see how much can be recovered since Lat and Long gives the specific point. If we have latitude and longitude in the missing columns, it is possible to recover province.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nunknown_rows <- acc %>%\n  filter(province_en == \"unknown\" | is.na(province_en))\n\nunknown_with_xy <- unknown_rows %>%\n  filter(!is.na(latitude), !is.na(longitude))\n\nunknown_no_xy <- unknown_rows %>%\n  filter(is.na(latitude) | is.na(longitude))\n\n\ntibble(\n  category      = c(\"Unknown province (total)\",\n                    \"→ with coordinates (recoverable)\",\n                    \"→ without coordinates (need manual or drop)\"),\n  n             = c(nrow(unknown_rows),\n                    nrow(unknown_with_xy),\n                    nrow(unknown_no_xy)),\n  pct_of_unknown = round(100 * n / nrow(unknown_rows), 1)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  category                                        n pct_of_unknown\n  <chr>                                       <int>          <dbl>\n1 Unknown province (total)                       34          100  \n2 → with coordinates (recoverable)               25           73.5\n3 → without coordinates (need manual or drop)     9           26.5\n```\n\n\n:::\n:::\n\n\nSo we can see that there are 25 coordinates that can actually be recovered from the 34 with missing province locations. This is good since 73.5% of missing values can be recovered.\n\nThrough analysis of the shapefile (not the csv which does look at province...) , ADM 2 looks into the district and not province. So it will not be possible to use our current ADM 2 shapefile of Thailand to attain the province values to need to link the coordinates. We will use ADM 1 instead. Now the data will be loaded in.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprovinces <- st_read(\"data/geospatial/Thai_province/geoBoundaries-THA-ADM1.shp\") %>%\n  st_transform(4326)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `geoBoundaries-THA-ADM1' from data source \n  `C:\\cjmheidii\\ISSS626 - Geospatial\\Hands-on_Ex\\data\\geospatial\\Thai_province\\geoBoundaries-THA-ADM1.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 77 features and 5 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 97.34381 ymin: 5.612851 xmax: 105.6368 ymax: 20.46483\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\n# Check the province name column to ensure we can use ADM1 \nnames(provinces)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"shapeName\"  \"shapeISO\"   \"shapeID\"    \"shapeGroup\" \"shapeType\" \n[6] \"geometry\"  \n```\n\n\n:::\n\n```{.r .cell-code}\n# Isolate the rows we want to recover, so it dosent affect the main dataset\nunknown_with_xy <- acc %>%\n  filter(\n    (province_en == \"unknown\" | is.na(province_en)) &\n      !is.na(latitude) & !is.na(longitude)\n  )\n\npts <- st_as_sf(\n  unknown_with_xy,\n  coords = c(\"longitude\", \"latitude\"),\n  crs = 4326\n)\n\n# Here is where the join is done to connect the datapoints\npts_joined <- st_join(pts, provinces, join = st_within)\npts_joined %>%\n  st_drop_geometry() %>%\n  select(acc_code, shapeName) %>%\n  head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 2\n  acc_code shapeName\n     <dbl> <chr>    \n1   572732 <NA>     \n2   573720 <NA>     \n3   574701 <NA>     \n4   574704 <NA>     \n5   575103 <NA>     \n6  1616332 <NA>     \n```\n\n\n:::\n\n```{.r .cell-code}\nmissed <- pts_joined %>% filter(is.na(shapeName))\nnrow(missed)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 8\n```\n\n\n:::\n\n```{.r .cell-code}\n# In case of any misses with the provinces, this is a fallback to link up to nearest province \nif (nrow(missed) > 0) {\n  idx <- st_nearest_feature(missed, provinces)\n  pts_joined$shapeName[is.na(pts_joined$shapeName)] <- provinces$shapeName[idx]\n}\n\n# Merge accounts back to actual dataset\nacc_joined <- acc %>%\n  left_join(\n    pts_joined %>%\n      st_drop_geometry() %>%\n      select(acc_code, recovered_province = shapeName),\n    by = \"acc_code\"\n  ) %>%\n  mutate(\n    province_en = ifelse(\n      province_en == \"unknown\" | is.na(province_en),\n      recovered_province,\n      province_en\n    )\n  ) %>%\n  select(-recovered_province)\n\nacc <- acc_joined\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Verification, now there should be 9 missing data points rather than 34!\nacc %>%\n  filter(is.na(province_en)) %>%\n  nrow()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9\n```\n\n\n:::\n:::\n\n\nNow that we've settled the 24 recoverable records of data, we will now remove the 9 missing data points where it is impossible to recover.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacc<- acc %>%\n  filter(!is.na(province_en))\n\n# Verify that there are now 0 rows with missing province\nacc %>%\n  filter(is.na(province_en)) %>%\n  nrow()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\n### Removal of Unnecessary Rows\n\nThe current dataset is from 2019-2022, since we are aiming to only look at 2022 data we want to drop the unnecessary rows (year 2019-2021).\n\n::: callout-note\nWe will only look at the range of year 2022 through the use of incident_datetime since we want to analyse the accidents that occurred in 2022 instead of report_datetime (refers to the date and time when the accident is recorded).\n\nThis is important because there time is needed after the accident has occurred for it to be recorded, resulting in a reporting lag. Therefore, this distinction is highlighted to show that the correct column is used for the filtering together with the importance of this distinction.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# The date and Time will be parsed to Thailand timezone using the mutate function, so hardware (computer) which is in Singapore timezone can accurately filter the data to year 2022. \nacc <- acc %>%\n  mutate(\n    incident_datetime = ymd_hms(incident_datetime, tz = \"Asia/Bangkok\"),\n    report_datetime   = ymd_hms(report_datetime,   tz = \"Asia/Bangkok\")\n  )\n\n\n# Filter so that only year 2022 data exists in current dataset \nacc<- acc %>%\n  filter(year(incident_datetime) == 2022)\n\n# Verify that the datetime is what we need\nnrow(acc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 21006\n```\n\n\n:::\n\n```{.r .cell-code}\nrange(acc$incident_datetime)  \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2022-01-01 00:01:00 +07\" \"2022-12-31 23:55:00 +07\"\n```\n\n\n:::\n:::\n\n\nNow below is a summary of the rows removed up till now.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(\n  Stage = c(\n    \"Raw import\",\n    \"After province recovery + drop unrecoverable\",\n    \"After temporal filter (year 2022)\"\n  ),\n  Rows = c(81735, 81701, 21006),\n  Removed = c(NA, 34, 60695)\n) %>%\n  gt() %>%\n  tab_header(title = \"Row Counts at Each Cleaning Stage\") %>%\n  cols_label(Stage = \"Cleaning Stage\", Rows = \"Rows Remaining\", Removed = \"Rows Removed\") %>%\n  fmt_number(columns = c(Rows, Removed), decimals = 0)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ffgfsejgzk\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ffgfsejgzk table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ffgfsejgzk thead, #ffgfsejgzk tbody, #ffgfsejgzk tfoot, #ffgfsejgzk tr, #ffgfsejgzk td, #ffgfsejgzk th {\n  border-style: none;\n}\n\n#ffgfsejgzk p {\n  margin: 0;\n  padding: 0;\n}\n\n#ffgfsejgzk .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ffgfsejgzk .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ffgfsejgzk .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ffgfsejgzk .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ffgfsejgzk .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ffgfsejgzk .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ffgfsejgzk .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ffgfsejgzk .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ffgfsejgzk .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ffgfsejgzk .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ffgfsejgzk .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ffgfsejgzk .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ffgfsejgzk .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ffgfsejgzk .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ffgfsejgzk .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ffgfsejgzk .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ffgfsejgzk .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ffgfsejgzk .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ffgfsejgzk .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ffgfsejgzk .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ffgfsejgzk .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ffgfsejgzk .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ffgfsejgzk .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ffgfsejgzk .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ffgfsejgzk .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ffgfsejgzk .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ffgfsejgzk .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ffgfsejgzk .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ffgfsejgzk .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ffgfsejgzk .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ffgfsejgzk .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ffgfsejgzk .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ffgfsejgzk .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ffgfsejgzk .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ffgfsejgzk .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ffgfsejgzk .gt_left {\n  text-align: left;\n}\n\n#ffgfsejgzk .gt_center {\n  text-align: center;\n}\n\n#ffgfsejgzk .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ffgfsejgzk .gt_font_normal {\n  font-weight: normal;\n}\n\n#ffgfsejgzk .gt_font_bold {\n  font-weight: bold;\n}\n\n#ffgfsejgzk .gt_font_italic {\n  font-style: italic;\n}\n\n#ffgfsejgzk .gt_super {\n  font-size: 65%;\n}\n\n#ffgfsejgzk .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ffgfsejgzk .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ffgfsejgzk .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ffgfsejgzk .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ffgfsejgzk .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ffgfsejgzk .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ffgfsejgzk .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ffgfsejgzk .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ffgfsejgzk div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"3\" class=\"gt_heading gt_title gt_font_normal gt_bottom_border\" style>Row Counts at Each Cleaning Stage</td>\n    </tr>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Stage\">Cleaning Stage</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Rows\">Rows Remaining</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Removed\">Rows Removed</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Stage\" class=\"gt_row gt_left\">Raw import</td>\n<td headers=\"Rows\" class=\"gt_row gt_right\">81,735</td>\n<td headers=\"Removed\" class=\"gt_row gt_right\">NA</td></tr>\n    <tr><td headers=\"Stage\" class=\"gt_row gt_left\">After province recovery + drop unrecoverable</td>\n<td headers=\"Rows\" class=\"gt_row gt_right\">81,701</td>\n<td headers=\"Removed\" class=\"gt_row gt_right\">34</td></tr>\n    <tr><td headers=\"Stage\" class=\"gt_row gt_left\">After temporal filter (year 2022)</td>\n<td headers=\"Rows\" class=\"gt_row gt_right\">21,006</td>\n<td headers=\"Removed\" class=\"gt_row gt_right\">60,695</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n### Removal of Columns\n\nNow we look at Removal of columns, where province_th and route columns will be removed.\n\n::: callout-note\nFrom the previous code input, we can see the first few rows of the data is displayed to have a rough sense of the data.\n\nThere is a \"Duplicated\" Column where \"province_th\" is the same as \"province_en\" but in the Thai language. Since we cannot understand Thai, we will remove this column instead of province_en.\n\nFurthermore, route column is redundant since the coordinates are given through the latitude and longitude data columns. The inconsistent description of junctions, highway numbers and sectors are also the reason why this column should not be used, since it will only cause more confusion in analysis process.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Drop unncessary columns \nacc<- acc %>% select(-route, -province_th)\n\n# Now to confirm the correct columns are dropped. We will expect to see 16 columns instead. (6x16)\nhead(acc) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 16\n  acc_code incident_datetime   report_datetime     province_en            agency\n     <dbl> <dttm>              <dttm>              <chr>                  <chr> \n1  6566872 2022-01-01 00:01:00 2022-01-02 11:45:00 Chai Nat               depar…\n2  6566880 2022-01-01 00:01:00 2022-01-02 11:44:00 Maha Sarakham          depar…\n3  5706553 2022-01-01 00:03:00 2022-02-09 08:41:00 Chumphon               depar…\n4  5485750 2022-01-01 00:05:00 2022-01-02 06:21:00 Phuket                 depar…\n5  5624452 2022-01-01 00:05:00 2022-01-24 09:59:00 Udon Thani             depar…\n6  6566842 2022-01-01 00:05:00 2022-01-02 11:46:00 Phra Nakhon Si Ayutth… depar…\n# ℹ 11 more variables: vehicle_type <chr>, presumed_cause <chr>,\n#   accident_type <chr>, number_of_vehicles_involved <dbl>,\n#   number_of_fatalities <dbl>, number_of_injuries <dbl>,\n#   weather_condition <chr>, latitude <dbl>, longitude <dbl>,\n#   road_description <chr>, slope_description <chr>\n```\n\n\n:::\n:::\n\n\n### Ensuring Unique rows in data\n\nEphasizing again on the importance of having each point to represent an independent event, it is imperative that every accident within the dataset is unique!\n\nTherefore, to make sure there is no duplicated rows `any(duplicated(acc))` is used to ensure that every accident (full row) is unique.\n\nTo double check, we also use the `any(duplicated(acc))` to verify that there is no duplicate or repeated observations in the cleaned dataset which looks at the account code itself which is said to be unique. Especially since any(duplicated(acc)) will not be able to detect that there is duplicate record of E.g Accident ABC if any other column within the 2 rows are different.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# This looks for duplicates across the entire row, where it only records if all values within one row is the same as another\nany(duplicated(acc))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n\n```{.r .cell-code}\n# This ensures that all acccount codes (acc_code) is different and unique, so that we arent looking at multiple accident accounts. \nsum(duplicated(acc$acc_code))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\nSince FALSE and 0 is returned its confirmed all records are unique, and we can proceed on with drawing out the plots.\n\n## Assumptions & Decisions made\n\n### Assumptions made\n\nSome assumptions made in this exercise for the analysis to be valid. The list is as follows\n\n#### Reliability of original Dataset\n\nThere is always the possibility of human error, where in this case human error can refer to personnel forgetting to record an accident that has occurred. So we will assume here that the data provided is fully representative of all accidents that occurred in 2022.\n\n#### Homogeneity\n\nIt is assumed that the risk of every accident occuring across Thailand is uniform, or exactly the same. In reality, there are many variables that can influence this risk level like the volume of traffic or level of maintenance of the roads or etc. This assumption will be put to allow exploratory trend detection.\n\n#### Independence\n\nWe assume that each accident is independent of each other. There can be times in reality where an accident can occur due to the occurrence of another, this is known as multi-vehicle crashes. Hence multiple points in this case will be recorded within these datasets, but we will assume in this exercise that all accidents are recorded as separate events.\n\n#### Isotropy\n\nWe assume here that the intensity of the accidents is the same in all directions. In reality, road networks are linear, so accidents are constrained to roads. So with the assumption, the analysis can be a relatively useful form of visualisation on risk.\n\n### Decisions made\n\nThe **Coordinate Reference System (CRS)** was decided to be changed within the Thailand Boundary from WGS 84 (EPSG:4326) to UTM Zone 47N (EPSG:32647). This is essential because UTM coordinates are in meters, which allows distance-based methods (bandwidth selection, Ripley's K, edge correction) to operate on meaningful planar distances rather than degrees.\n\n## Overview plot\n\nThis overview plot is made to ensure that the data is loaded properly and there are no errors in data manipulation or cleaning.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# as mentioned, the CRS is changed from the WGS 84 here and transformed to UTM Zone 47N -> EPSG:32647\nacc <- acc %>%\n  filter(!is.na(latitude), !is.na(longitude)) %>%\n  st_as_sf(coords = c(\"longitude\", \"latitude\"), crs = 4326)\n\nacc <- st_transform(acc, 32647)\nthai_map <- st_transform(thai_map,    32647)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Now we plot an overview on the tmap. \ntm_shape(thai_map) +\n  tm_polygons(col = \"grey95\", border.col = \"grey70\", lwd = 0.1) +\n  tm_shape(acc) +\n  tm_dots(col = \"red\", size = 0.02, alpha = 0.5) +\n  tm_layout(frame = FALSE)\n```\n\n::: {.cell-output-display}\n![](Take-Home_ex01_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n::: callout-note\nThe reason why Tmap is being used instead of the usual plot() :\n\ntmap is a package helps to render the ploygons better than plots, preventing overlapping borders like what plot() will do. Basically it is better at rendering and plotting the multi-ploygon background more clearly.\n:::\n\n# Task 2: First-Order Point Pattern Analysis\n\n## Computing accident STKDE by Month\n\nWhat we currently have is only the overall accident distribution in the entire year of 2022, but we cannot see where and when the accidents would occur together.\n\nWith the STKDE by month helping to estimate a 3D intensity surface on 1 plot per month for a total of 12 plots, it gives a smoothed continuous surface to help compare the intensity of accidents. We can see which areas within Thailand have a high accident intensity and in which months the intensity is concentrated.\n\nTherefore STKDE by month is done for the 1st Order Point Analysis because it provides the insights on the where and when the accident happens together, or the analysis of both spatial and temporal dimensions simultaneously.\n\n### Step 1: Converting to OWIN format\n\nOur current file is in the sf object with 70 polygon regions. However, for the `ppp` and STKDE to be conducted we need to transform it to a single OWIN format to conduct the First-Order Pattern Analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Union all provinces into a single polygon\nthailand_sf <- provinces %>%\n  st_make_valid() %>%\n  st_union() %>%\n  st_zm(drop = TRUE, what = \"ZM\") %>%\n  st_transform(crs = 32647)\n\n# Convert to OWIN\nthailand_owin <- as.owin(thailand_sf)\n\n# We put in class and summary to ensure that our we have indeed converted this to OWIN format as required. \nclass(thailand_owin)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"owin\"\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(thailand_owin)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWindow: polygonal boundary\n70 separate polygons (no holes)\n            vertices        area relative.area\npolygon 1      68307 5.13481e+11      9.96e-01\npolygon 2        398 6.22860e+06      1.21e-05\npolygon 3        614 4.22645e+06      8.20e-06\npolygon 4        343 5.28725e+06      1.03e-05\npolygon 5         65 1.38434e+07      2.68e-05\npolygon 6         65 4.18966e+06      8.13e-06\npolygon 7        616 5.12128e+06      9.93e-06\npolygon 8         28 1.15450e+06      2.24e-06\npolygon 9        793 2.10501e+08      4.08e-04\npolygon 10        85 3.76729e+06      7.31e-06\npolygon 11        48 2.76015e+06      5.35e-06\npolygon 12       207 1.42079e+06      2.76e-06\npolygon 13        49 2.02952e+06      3.94e-06\npolygon 14       484 1.22550e+07      2.38e-05\npolygon 15        48 2.46727e+06      4.78e-06\npolygon 16       745 1.11694e+08      2.17e-04\npolygon 17        38 1.43222e+06      2.78e-06\npolygon 18        88 1.02373e+06      1.99e-06\npolygon 19       147 1.89559e+06      3.68e-06\npolygon 20       209 1.48895e+06      2.89e-06\npolygon 21       251 1.88460e+07      3.65e-05\npolygon 22        42 1.08756e+06      2.11e-06\npolygon 23        14 2.17582e+06      4.22e-06\npolygon 24        44 2.73306e+06      5.30e-06\npolygon 25       472 2.03006e+07      3.94e-05\npolygon 26       976 1.22167e+08      2.37e-04\npolygon 27       448 1.66910e+07      3.24e-05\npolygon 28        35 1.53899e+06      2.98e-06\npolygon 29        47 4.82003e+06      9.35e-06\npolygon 30      1703 2.35879e+08      4.57e-04\npolygon 31        95 1.54700e+07      3.00e-05\npolygon 32        12 1.24960e+06      2.42e-06\npolygon 33       389 1.33179e+07      2.58e-05\npolygon 34       180 8.26376e+06      1.60e-05\npolygon 35        16 2.85487e+06      5.54e-06\npolygon 36       382 6.72333e+06      1.30e-05\npolygon 37       134 1.83542e+07      3.56e-05\npolygon 38       475 9.54313e+07      1.85e-04\npolygon 39        39 1.33566e+06      2.59e-06\npolygon 40       229 6.67462e+07      1.29e-04\npolygon 41        32 1.98965e+06      3.86e-06\npolygon 42        45 6.59422e+06      1.28e-05\npolygon 43       140 3.86996e+06      7.51e-06\npolygon 44        94 3.00058e+06      5.82e-06\npolygon 45      3243 5.12443e+08      9.94e-04\npolygon 46       599 3.57589e+07      6.93e-05\npolygon 47       432 8.79243e+07      1.71e-04\npolygon 48        38 2.03000e+06      3.94e-06\npolygon 49       233 1.38498e+07      2.69e-05\npolygon 50        84 3.73855e+06      7.25e-06\npolygon 51       302 7.99302e+06      1.55e-05\npolygon 52       115 4.66422e+06      9.05e-06\npolygon 53       265 9.92294e+06      1.92e-05\npolygon 54        13 2.20961e+06      4.29e-06\npolygon 55       225 1.70308e+06      3.30e-06\npolygon 56       135 1.20558e+06      2.34e-06\npolygon 57       656 6.27813e+07      1.22e-04\npolygon 58       789 7.80730e+07      1.51e-04\npolygon 59       353 4.69610e+06      9.11e-06\npolygon 60       188 2.40409e+06      4.66e-06\npolygon 61       206 3.59613e+06      6.97e-06\npolygon 62       173 7.59796e+06      1.47e-05\npolygon 63       187 1.65836e+06      3.22e-06\npolygon 64        54 3.26622e+07      6.33e-05\npolygon 65       258 1.42628e+06      2.77e-06\npolygon 66       809 1.52418e+08      2.96e-04\npolygon 67      2456 2.87236e+07      5.57e-05\npolygon 68       962 2.90690e+07      5.64e-05\npolygon 69       551 4.03691e+06      7.83e-06\npolygon 70       873 2.04046e+06      3.96e-06\nenclosing rectangle: [325229.8, 1213613.6] x [620840, 2263214.7] units\n                     (888400 x 1642000 units)\nWindow area = 5.1564e+11 square units\nFraction of frame area: 0.353\n```\n\n\n:::\n:::\n\n\nSince current class here is now OWIN we are good to go to step 2.\n\n### Step 2 : Extracting Data by Month\n\nwhen we use `ppp` , it only accepts numeric or character marks. However currently we only have the date (incident_datetime) by a date format. Therefore, we will have to extract out the `Month_num` (1 to 12 from January to December) and `Month_fac` to produce readable facet labels without inline conversion.\n\n`DayofYear` is also extracted for now in case of the need for analysis of each specific day of the year.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacc <- acc %>%\n  mutate(\n    DayofYear = yday(incident_datetime),\n    Month_num = month(incident_datetime),\n    Month_fac = month(incident_datetime, label = TRUE, abbr = FALSE)\n  )\n```\n:::\n\n\n### Step 3 : Visualising accidents by month\n\nBefore computing the KDE, it is important to plot a faceted point map (one small map of Thailand per month).\n\nThis is a first order visualisation of the data to understand the spatial distribution of accidents across the year and if there is any seasonality before computing the KDE. It also acts as the baseline before the STKDE is done to allow a comparison to be done.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(thailand_sf) +\n  tm_polygons() +\n  tm_shape(acc) +\n  tm_dots(size = 0.1) +\n  tm_facets(by = \"Month_fac\",\n            free.coords = FALSE,\n            drop.units = TRUE)\n```\n\n::: {.cell-output-display}\n![](Take-Home_ex01_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n::: callout-important\n**Analysis of plot.**\n\nFrom the plot, it can be seen that April and December have a heavier distribution throughout the months in the year, which ties in the monthly trends in Thailand with higher vehicle numbers on the road from the [Songkran Holiday travelling in April](https://he02.tci-thaijo.org/index.php/agstjournal/article/view/275930) and New Year Holiday travels in December.\n\nHowever it is to note that in all 12 months, there is a darker concentration around the Bangkok and central provinces proving that Bangkok area is a permanent high-risk accident zone. In contrast, the North-Eastern Region in Thailand is showing fewer dots in the visuals throughout the year reflecting a lower accident volume assuming that the data provided is fully representative of all accidents that occurred in 2022 (as mentioned in assumptions made).\n:::\n\n### Step 4 : coverting to ppp\n\nSince we are looking at the Month specifically we will keep only the Month number column and use it to convert to ppp.\n\nIt is also recommended to check again here to see if there are duplicated units. Usually this is done to prevent any inaccuracies when analysing data. However in this case, it is expected for there to be multiple crashes at the same intersection so it's fine for there to be duplicate values. The presence of duplicate values if any violates the strict independence assumption of point pattern analysis, but the events are retained because they represent genuinely distinct accidents. Therefore, the duplicate check is just to note that there are these sort of multi-crash accidents, and highlight the presence of this analytical limitation when conducting the analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Keep only Month_num column\nacc_month <- acc %>% select(Month_num)\n\n# Convert to ppp\nacc_month_ppp <- as.ppp(acc_month)\n\n# Check for duplicates \nany(duplicated(acc_month_ppp))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\n### Step 5 : Compute STKDE\n\nNow the STKDE is finally computed using the `spattemp.density` function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacc_month_owin <- acc_month_ppp[thailand_owin]\nsummary(acc_month_owin)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern:  20815 points\nAverage intensity 4.036734e-08 points per square unit\n\n*Pattern contains duplicated points*\n\nCoordinates are given to 10 decimal places\n\nmarks are numeric, of type 'double'\nSummary:\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  1.000   3.000   6.000   6.328   9.000  12.000 \n\nWindow: polygonal boundary\n70 separate polygons (no holes)\n            vertices        area relative.area\npolygon 1      68307 5.13481e+11      9.96e-01\npolygon 2        398 6.22860e+06      1.21e-05\npolygon 3        614 4.22645e+06      8.20e-06\npolygon 4        343 5.28725e+06      1.03e-05\npolygon 5         65 1.38434e+07      2.68e-05\npolygon 6         65 4.18966e+06      8.13e-06\npolygon 7        616 5.12128e+06      9.93e-06\npolygon 8         28 1.15450e+06      2.24e-06\npolygon 9        793 2.10501e+08      4.08e-04\npolygon 10        85 3.76729e+06      7.31e-06\npolygon 11        48 2.76015e+06      5.35e-06\npolygon 12       207 1.42079e+06      2.76e-06\npolygon 13        49 2.02952e+06      3.94e-06\npolygon 14       484 1.22550e+07      2.38e-05\npolygon 15        48 2.46727e+06      4.78e-06\npolygon 16       745 1.11694e+08      2.17e-04\npolygon 17        38 1.43222e+06      2.78e-06\npolygon 18        88 1.02373e+06      1.99e-06\npolygon 19       147 1.89559e+06      3.68e-06\npolygon 20       209 1.48895e+06      2.89e-06\npolygon 21       251 1.88460e+07      3.65e-05\npolygon 22        42 1.08756e+06      2.11e-06\npolygon 23        14 2.17582e+06      4.22e-06\npolygon 24        44 2.73306e+06      5.30e-06\npolygon 25       472 2.03006e+07      3.94e-05\npolygon 26       976 1.22167e+08      2.37e-04\npolygon 27       448 1.66910e+07      3.24e-05\npolygon 28        35 1.53899e+06      2.98e-06\npolygon 29        47 4.82003e+06      9.35e-06\npolygon 30      1703 2.35879e+08      4.57e-04\npolygon 31        95 1.54700e+07      3.00e-05\npolygon 32        12 1.24960e+06      2.42e-06\npolygon 33       389 1.33179e+07      2.58e-05\npolygon 34       180 8.26376e+06      1.60e-05\npolygon 35        16 2.85487e+06      5.54e-06\npolygon 36       382 6.72333e+06      1.30e-05\npolygon 37       134 1.83542e+07      3.56e-05\npolygon 38       475 9.54313e+07      1.85e-04\npolygon 39        39 1.33566e+06      2.59e-06\npolygon 40       229 6.67462e+07      1.29e-04\npolygon 41        32 1.98965e+06      3.86e-06\npolygon 42        45 6.59422e+06      1.28e-05\npolygon 43       140 3.86996e+06      7.51e-06\npolygon 44        94 3.00058e+06      5.82e-06\npolygon 45      3243 5.12443e+08      9.94e-04\npolygon 46       599 3.57589e+07      6.93e-05\npolygon 47       432 8.79243e+07      1.71e-04\npolygon 48        38 2.03000e+06      3.94e-06\npolygon 49       233 1.38498e+07      2.69e-05\npolygon 50        84 3.73855e+06      7.25e-06\npolygon 51       302 7.99302e+06      1.55e-05\npolygon 52       115 4.66422e+06      9.05e-06\npolygon 53       265 9.92294e+06      1.92e-05\npolygon 54        13 2.20961e+06      4.29e-06\npolygon 55       225 1.70308e+06      3.30e-06\npolygon 56       135 1.20558e+06      2.34e-06\npolygon 57       656 6.27813e+07      1.22e-04\npolygon 58       789 7.80730e+07      1.51e-04\npolygon 59       353 4.69610e+06      9.11e-06\npolygon 60       188 2.40409e+06      4.66e-06\npolygon 61       206 3.59613e+06      6.97e-06\npolygon 62       173 7.59796e+06      1.47e-05\npolygon 63       187 1.65836e+06      3.22e-06\npolygon 64        54 3.26622e+07      6.33e-05\npolygon 65       258 1.42628e+06      2.77e-06\npolygon 66       809 1.52418e+08      2.96e-04\npolygon 67      2456 2.87236e+07      5.57e-05\npolygon 68       962 2.90690e+07      5.64e-05\npolygon 69       551 4.03691e+06      7.83e-06\npolygon 70       873 2.04046e+06      3.96e-06\nenclosing rectangle: [325229.8, 1213613.6] x [620840, 2263214.7] units\n                     (888400 x 1642000 units)\nWindow area = 5.1564e+11 square units\nFraction of frame area: 0.353\n```\n\n\n:::\n\n```{.r .cell-code}\nst_kde <- spattemp.density(acc_month_owin)\nsummary(st_kde)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatiotemporal Kernel Density Estimate\n\nBandwidths\n  h = 38159.91 (spatial)\n  lambda = 0.0079 (temporal)\n\nNo. of observations\n  20815 \n\nSpatial bound\n  Type: polygonal\n  2D enclosure: [325229.8, 1213614] x [620840, 2263215]\n\nTemporal bound\n  [1, 12]\n\nEvaluation\n  128 x 128 x 12 trivariate lattice\n  Density range: [7.353343e-15, 2.439755e-10]\n```\n\n\n:::\n:::\n\n\nThe `spattemp.density()` function has estimated a Spatial bandwidth of 38159.91 (\\~38.16km). This is with the smoothing distance in UTM Zone 47N metres. It is known that a larger `h` produces a smoother, more generalised surface while a smaller `h` reveals local hot spots. Overall it is decided that the spatial bandwidth should not be further changed it balances detail against noise given the irregular shape of Thailand's boundary.\n\nThe temporal bandwidth is estimated to be lambda = 0.0079 (in units of the temporal range). Since time was rescaled to `[1, 12]` months, we have a narrow temporal smoothing window of about 0.1 month, which means that the density surface will change sharply month-to-month which is best to emphasize the high intensity time scope of April and December. Therefore edge correction is applied to reduce the bias near Thailand's border, where points outside the boundary cannot be observed but still contribute to the intensity estimate.\n\nThe trivariate density is normalised and conditioned to allow each monthly slice to integrate to 1 and make for direct visual comparison across months.\n\n### Step 6 : Plot out STKDE\n\nAfter the computation, the STKDE is plotted out.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# The plot is split to show 6 at a time, 2 rows 3 columns per page so each month STKDE is large enough to see to make proper analysis. \ntims <- c(1,2,3,4,5,6,7,8,9,10,11,12)\npar(mfcol=c(2,3))\nfor(i in tims){ \n  plot(st_kde, i, \n       override.par=FALSE, \n       fix.range=TRUE, \n       main=paste(\"KDE at month\",i))\n}\n```\n\n::: {.cell-output-display}\n![](Take-Home_ex01_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Take-Home_ex01_files/figure-html/unnamed-chunk-20-2.png){width=672}\n:::\n:::\n\n\n::: callout-important\n**Analysis of plot.**\n\nThe STKDE visualizations confirm the initial findings from our raw monthly map. More specifically :\n\n1.  April and December peaks in accident numbers with January coming behind as a close third.\n\n2.  Bangkok regions is a hot spot for accident occurrence through the red colour intensity in those months\n\nHowever it also refines a few points. First, the South peninsula area actually shows a low density per unit area rather than the entire area being a hot spot. The prominence of the entire South Peninsula was rather shown in the initial monthly plots because of the raw accident counts inflating the concentration of accident rates.\n\nFurthermore, elaborating on intensity, other than Bangkok, the entire country shows a uniformly low accident intensity given the blue colour scale across all these areas in all months. This proves that the Bangkok Region is the single main dominant accident hot spot in Thailand for the year 2022.\n:::\n\n## Computing Death Toll using STKDE by Month\n\nThere are different levels of severity of vehicle accidents, from a light collision without injuries to heavy injuries in the ICU or even death.\n\nTherefore, we will also look at the death toll within Thailand from accidents using STKDE by month again.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter to fatal accidents only\nacc_fatal <- acc %>%\n  filter(number_of_fatalities > 0) %>%\n  mutate(\n    Month_num = month(incident_datetime),\n    Month_fac = month(incident_datetime, label = TRUE, abbr = FALSE)\n  )\n\n# Convert to ppp\nacc_fatal_month <- acc_fatal %>% select(Month_num)\nacc_fatal_ppp <- as.ppp(acc_fatal_month)\nacc_fatal_owin <- acc_fatal_ppp[thailand_owin]\n\n# Conduct STKDE\nst_kde_fatal <- spattemp.density(acc_fatal_owin)\nsummary(st_kde_fatal)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatiotemporal Kernel Density Estimate\n\nBandwidths\n  h = 66182.92 (spatial)\n  lambda = 0.0417 (temporal)\n\nNo. of observations\n  2273 \n\nSpatial bound\n  Type: polygonal\n  2D enclosure: [325229.8, 1213614] x [620840, 2263215]\n\nTemporal bound\n  [1, 12]\n\nEvaluation\n  128 x 128 x 12 trivariate lattice\n  Density range: [1.799614e-14, 1.756263e-11]\n```\n\n\n:::\n\n```{.r .cell-code}\n# Plotting visualisation\n\npar(mfcol = c(2, 3))\nfor (i in 1:12) {\n  plot(st_kde_fatal, i, override.par = FALSE, fix.range = TRUE,\n       main = paste(\"Fatal KDE at month\", i))\n}\n```\n\n::: {.cell-output-display}\n![](Take-Home_ex01_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Take-Home_ex01_files/figure-html/unnamed-chunk-21-2.png){width=672}\n:::\n:::\n\n\n::: callout-important\n**Analysis of plot.**\n\nNow this plot on the death toll reveals major different trends than the overall accident plots, suggesting that accident frequency and severity are following different spatial and temporal patterns.\n\nHere, the fatal accident intensity is elevated in Northern, North-Eastern Thailand, and Bangkok in mainly the January and December months, where January has replaced April as the peak month in regards to fatality of accidents.\n\nSince the rural roads are mainly in the North and North-East regions of Thailand, it fits the general fact that rural roads generates fewer but higher severity accidents leading to higher fatal accident rates and urban areas will have more low speed collision which is usually not as severe.\n:::\n\n## Preliminary Clark Evans Test (Highlighted Regions)\n\nNow that the overview analysis of the entire country of Thailand is done, there are 3 regions that are flagged out to be accident hotspots or have a higher fatality intensity :\n\n- **Bangkok Metropolitan Region (BMR)** — the dominant urban accident hotspot.\n- **Northern Thailand** — rural, mountainous, elevated fatality intensity.\n- **North-Eastern Thailand (Isan)** — rural, elevated fatality intensity.\n\nTherefore even though the main region of study should be in the Bangkok region, it is deemed necessary to study the 3 regions in more detail due to the alarming impact of fatalities in these 3 regions. Especially since the SPKDE only helps to say where in Thailand are the accidents more intense, and not if the specific accidents are clustered or dispersed. The Clark-Evans Test however, provides statistical evidence that the visual hot spot you saw in the STKDE is real, not a coincidence of plotting, which is also why we are looking at the highlighed Regions throuh the Clark Evans Testing for our First order SPAA.\n\nThe Clark-Evans Test assumes there is no duplicated points. So it is required to ensure that we check there is no duplicated points since any duplicated points will inflate the clustering signal.\n\n### Step 1 : Defining the Study Regions\n\nWe have our regions that we want to drill into to study. However the regions are made up of a numerous number of provinces, where our data only has the column of provinces or districts. Therefore, we have to put this additional step to define what our study regions are.\n\nThis is a code to confirm on the provinces within our dataset as well as the spelling in each one of them before proceeding with further analysis. If the spelling is wrong, we will have issues in writing out the right code.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprovinces %>%\n  st_drop_geometry() %>%\n  pull(shapeName) %>%\n  sort() %>%\n  print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"Amnat Charoen Province\"            \"Ang Thong Province\"               \n [3] \"Bangkok\"                           \"Bueng Kan Province\"               \n [5] \"Buri Ram Province\"                 \"Chachoengsao Province\"            \n [7] \"Chai Nat Province\"                 \"Chaiyaphum Province\"              \n [9] \"Chanthaburi Province\"              \"Chiang Mai Province\"              \n[11] \"Chiang Rai Province\"               \"Chon Buri Province\"               \n[13] \"Chumphon Province\"                 \"Kalasin\"                          \n[15] \"Kamphaeng Phet Province\"           \"Kanchanaburi Province\"            \n[17] \"Khon Kaen Province\"                \"Krabi Province\"                   \n[19] \"Lampang Province\"                  \"Lamphun Province\"                 \n[21] \"Loei Province\"                     \"Lopburi Province\"                 \n[23] \"Mae Hong Son Province\"             \"Maha Sarakham Province\"           \n[25] \"Mukdahan Province\"                 \"Nakhon Nayok Province\"            \n[27] \"Nakhon Pathom Province\"            \"Nakhon Phanom Province\"           \n[29] \"Nakhon Ratchasima Province\"        \"Nakhon Sawan Province\"            \n[31] \"Nakhon Si Thammarat Province\"      \"Nan Province\"                     \n[33] \"Narathiwat Province\"               \"Nong Bua Lam Phu Province\"        \n[35] \"Nong Khai Province\"                \"Nonthaburi Province\"              \n[37] \"Pathum Thani Province\"             \"Pattani Province\"                 \n[39] \"Phangnga Province\"                 \"Phatthalung Province\"             \n[41] \"Phayao Province\"                   \"Phetchabun Province\"              \n[43] \"Phetchaburi Province\"              \"Phichit Province\"                 \n[45] \"Phitsanulok Province\"              \"Phra Nakhon Si Ayutthaya Province\"\n[47] \"Phrae Province\"                    \"Phuket Province\"                  \n[49] \"Prachin Buri Province\"             \"Prachuap Khiri Khan Province\"     \n[51] \"Ranong Province\"                   \"Ratchaburi Province\"              \n[53] \"Rayong Province\"                   \"Roi Et Province\"                  \n[55] \"Sa Kaeo Province\"                  \"Sakon Nakhon Province\"            \n[57] \"Samut Prakan Province\"             \"Samut Sakhon Province\"            \n[59] \"Samut Songkhram Province\"          \"Saraburi Province\"                \n[61] \"Satun Province\"                    \"Si Sa Ket Province\"               \n[63] \"Sing Buri Province\"                \"Songkhla Province\"                \n[65] \"Sukhothai Province\"                \"Suphan Buri Province\"             \n[67] \"Surat Thani Province\"              \"Surin Province\"                   \n[69] \"Tak Province\"                      \"Trang Province\"                   \n[71] \"Trat Province\"                     \"Ubon Ratchathani Province\"        \n[73] \"Udon Thani Province\"               \"Uthai Thani Province\"             \n[75] \"Uttaradit Province\"                \"Yala Province\"                    \n[77] \"Yasothon Province\"                \n```\n\n\n:::\n:::\n\n\nTherefore, we will be using the following provinces (decided after research on the definition of the Bangkok Metropolitan Region (BMR), Northern Thailand and North Eastern Thailand). As shown in the code chunk below, the 3 regions that we want to screen in for the analysis are now generated here.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# BMR Region \nbmr_provinces <- c(\n  \"Bangkok\",\n  \"Nonthaburi Province\",\n  \"Pathum Thani Province\",\n  \"Samut Prakan Province\",\n  \"Samut Sakhon Province\",\n  \"Nakhon Pathom Province\"\n)\n\n# Northern Thailand\nnorth_provinces <- c(\n  \"Chiang Mai Province\",\n  \"Chiang Rai Province\",\n  \"Lampang Province\",\n  \"Lamphun Province\",\n  \"Mae Hong Son Province\",\n  \"Nan Province\",\n  \"Phayao Province\",\n  \"Phrae Province\",\n  \"Uttaradit Province\"\n)\n\n# North-Eastern Thailand\nnortheast_provinces <- c(\n  \"Kalasin\",\n  \"Khon Kaen Province\",\n  \"Chaiyaphum Province\",\n  \"Nakhon Phanom Province\",\n  \"Nakhon Ratchasima Province\",\n  \"Bueng Kan Province\",\n  \"Maha Sarakham Province\",\n  \"Mukdahan Province\",\n  \"Yasothon Province\",\n  \"Roi Et Province\",\n  \"Loei Province\",\n  \"Sakon Nakhon Province\",\n  \"Surin Province\",\n  \"Nong Khai Province\",\n  \"Nong Bua Lam Phu Province\",\n  \"Amnat Charoen Province\",\n  \"Udon Thani Province\",\n  \"Ubon Ratchathani Province\",\n  \"Buri Ram Province\",\n  \"Si Sa Ket Province\"\n)\n```\n:::\n\n\n### Step 2 : Building the Region Objects\n\nNow we will build the region objects\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_region <- function(prov_names, region_name) {\n  sf_obj <- provinces %>%\n    filter(shapeName %in% prov_names) %>%\n    st_make_valid() %>%\n    st_transform(32647)\n  owin_obj <- as.owin(sf_obj %>% st_union() %>% st_zm(drop = TRUE, what = \"ZM\"))\n  cat(region_name, \":\", nrow(sf_obj), \"provinces\\n\")\n  list(sf = sf_obj, owin = owin_obj)\n}\n\nbmr   <- make_region(bmr_provinces,       \"BMR\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBMR : 6 provinces\n```\n\n\n:::\n\n```{.r .cell-code}\nnorth <- make_region(north_provinces,     \"Northern\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNorthern : 9 provinces\n```\n\n\n:::\n\n```{.r .cell-code}\nne    <- make_region(northeast_provinces, \"North-Eastern\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNorth-Eastern : 20 provinces\n```\n\n\n:::\n:::\n\n\n### Step 3 : Generating Clark-Evans and KDE\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# BMR\nacc_bmr <- acc %>% st_filter(bmr$sf, .predicate = st_within)\nbmr_ppp <- as.ppp(acc_bmr); Window(bmr_ppp) <- bmr$owin\nce_bmr  <- clarkevans.test(bmr_ppp, correction = \"none\")\nce_bmr\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tClark-Evans test\n\tNo edge correction\n\tZ-test\n\ndata:  bmr_ppp\nR = 0.26515, p-value < 2.2e-16\nalternative hypothesis: two-sided\n```\n\n\n:::\n\n```{.r .cell-code}\n# Northern\nacc_north <- acc %>% st_filter(north$sf, .predicate = st_within)\nnorth_ppp <- as.ppp(acc_north); Window(north_ppp) <- north$owin\nce_north  <- clarkevans.test(north_ppp, correction = \"none\")\nce_north\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tClark-Evans test\n\tNo edge correction\n\tZ-test\n\ndata:  north_ppp\nR = 0.3014, p-value < 2.2e-16\nalternative hypothesis: two-sided\n```\n\n\n:::\n\n```{.r .cell-code}\n# North-Eastern\nacc_ne <- acc %>% st_filter(ne$sf, .predicate = st_within)\nne_ppp <- as.ppp(acc_ne); Window(ne_ppp) <- ne$owin\nce_ne  <- clarkevans.test(ne_ppp, correction = \"none\")\nce_ne\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tClark-Evans test\n\tNo edge correction\n\tZ-test\n\ndata:  ne_ppp\nR = 0.41935, p-value < 2.2e-16\nalternative hypothesis: two-sided\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1, 3))\n\nplot(\n  st_geometry(bmr$sf),\n  main = \"Bangkok Metropolitan Region\"\n)\n\nplot(\n  st_geometry(north$sf),\n  main = \"Northern Thailand\"\n)\n\nplot(\n  st_geometry(ne$sf),\n  main = \"North-Eastern Thailand\"\n)\n```\n\n::: {.cell-output-display}\n![](Take-Home_ex01_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\n### Step 4: Creating OWIN objects\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbmr_owin   <- bmr$owin\nnorth_owin <- north$owin\nne_owin    <- ne$owin\n```\n:::\n\n\n### Step 5: Combination of OWIN and Point events\n\nWe have to put the acc\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacc_ppp <- as.ppp(acc)\nclass(acc_ppp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"ppp\"\n```\n\n\n:::\n:::\n\n\nIn usual circumstances, it is possible to directly convert the OWIN objects to ppp using ppp\\[owin\\]. However the current Thailand boundaries are defined using very detailed polygons with many vertices in the bounary rings. Thus it is required to simplify the OWIN to ensure that the computation is properly reduced. The analytical results below will not be changed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Simplification of OWIN object using st_simplify \nmake_simple_owin <- function(sf_obj, tol_m) {\n  sf_obj %>%\n    st_make_valid() %>%\n    st_simplify(dTolerance = tol_m, preserveTopology = TRUE) %>%\n    st_union() %>%\n    st_zm(drop = TRUE, what = \"ZM\") %>%\n    as.owin()\n}\n\nbmr_owin   <- make_simple_owin(bmr$sf,   tol_m = 2000)\nnorth_owin <- make_simple_owin(north$sf, tol_m = 3000)\nne_owin    <- make_simple_owin(ne$sf,    tol_m = 3000)\n# now we can convert to ppp \nacc_bmr_ppp   <- acc_ppp[bmr_owin]\nacc_north_ppp <- acc_ppp[north_owin]\nacc_ne_ppp    <- acc_ppp[ne_owin]\n```\n:::\n\n\n### Step 6: Rescaling from m to km\n\nCurrently the dataset is set to be in metres (UTM coordinates). So all the bandwidths and distances will be in enormous numbers within all the plots and calculations will be tough to read and interpret if the rescaling not be done.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacc_bmr_ppp.km   <- rescale.ppp(acc_bmr_ppp,   1000, \"km\")\nacc_north_ppp.km <- rescale.ppp(acc_north_ppp, 1000, \"km\")\nacc_ne_ppp.km    <- rescale.ppp(acc_ne_ppp,    1000, \"km\")\n```\n:::\n\n\n### Step 7 : Plotting\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(2, 2))\n\nplot(unmark(acc_bmr_ppp.km), main = \"BMR\",cex = 0.5)\nplot(unmark(acc_north_ppp.km), main = \"Northern Thailand\",cex = 0.5)\nplot(unmark(acc_ne_ppp.km), main = \"North-Eastern Thailand\", cex = 0.5)\n\npar(mfrow = c(1, 1))\n```\n\n::: {.cell-output-display}\n![](Take-Home_ex01_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\nnote : The analysis of the plots are included within the Clark Evans statistical testing.\n\n### Clark-Evans Statistical Testing\n\nNow that the plots are out and we can see where in the 3 regions are the accidents are clustered or spread out at, we conduct the Clark Evans statisitical testing to see if the results are significant.\n\n#### BMR\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclarkevans.test(acc_bmr_ppp,\n                correction=\"none\",\n                clipregion=NULL,\n                alternative=c(\"two.sided\"),\n                nsim=999)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tClark-Evans test\n\tNo edge correction\n\tZ-test\n\ndata:  acc_bmr_ppp\nR = 0.26425, p-value < 2.2e-16\nalternative hypothesis: two-sided\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(duplicated(acc_bmr_ppp))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\nSince p \\< 2.2 × 10⁻¹⁶ \\<0.05 it proves that the results are highly significant and the accidents in the Bangkok Metropolitan Region has a highly significant spatial clustering. With the R =0.265, it shows the observed average nearest neighbour distance is at 73.5% closer than normal to consider it as spatial randomness. Therefore with reference from the Clark Evans where there are very distinct lines on the highways of the Bangkok Metropolitan Region, these spots are where the concentrated accidents are which are the areas proven where the government needs to intervene to have the most impact in regards to the accident occurrences.\n\n#### North-Eastern Thailand\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclarkevans.test(acc_ne_ppp,\n                correction=\"none\",\n                clipregion=NULL,\n                alternative=c(\"two.sided\"),\n                nsim=999)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tClark-Evans test\n\tNo edge correction\n\tZ-test\n\ndata:  acc_ne_ppp\nR = 0.41683, p-value < 2.2e-16\nalternative hypothesis: two-sided\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(duplicated(acc_ne_ppp))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\nSince p \\< 2.2 × 10⁻¹⁶ \\<0.05, it proves that the results are highly significant and the accidents in the Thailand Northern East Region has a highly significant spatial clustering, though less of an extent than the Bangkok Metropolitan region. With the R =0.41935, it shows the observed average nearest neighbour distance is at 59.1% closer than normal to consider it as spatial randomness. Therefore with reference from the Clark Evans plot where the accidents are more spread out across Thailand as compared with the other 2 plots, but when looking close higher accident intensity areas can still be seen, it supports the fact that the Bangkok Metropolitan region is more clustered that the Northern East region. These areas in the Northern East region are the areas where the government needs to intervene to have the most impact in regards to the accident occurrences.\n\n#### Northern Thailand\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclarkevans.test(acc_north_ppp,\n                correction=\"none\",\n                clipregion=NULL,\n                alternative=c(\"two.sided\"),\n                nsim=999)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tClark-Evans test\n\tNo edge correction\n\tZ-test\n\ndata:  acc_north_ppp\nR = 0.29995, p-value < 2.2e-16\nalternative hypothesis: two-sided\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(duplicated(acc_north_ppp))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\nSince p \\< 2.2 × 10⁻¹⁶ \\<0.05, it proves that the results are highly significant and the accidents in the Bangkok Metropolitan Region has a highly significant spatial clustering. With the R =0.3014, it shows the observed average nearest neighbour distance is at 70.9% closer than normal to consider it as spatial randomness. Therefore with reference from the Clark Evans plot where there are darker intensity points plotted in the bottom area of Northern Thailand, these spots are where the concentrated accidents are which are the areas proven where the government needs to intervene to have the most impact in regards to the accident occurrences.\n\n## Analysis & Recommendations\n\nFrom the analysis, it is known that Bangkok is a persistent hotspot for accidents to occur, especially in the holidays of April and December. However, in January and December the accident fatality intensity spikes at the North and Northeast Regions of Thailand.\n\nIt is proven that these observations are strongly significant given the p \\< 2.2 × 10⁻¹⁶ \\<0.05 in the Clark Evans test in all tested regions where accident intensity are shown to be stronger. And that all highlighted regions (BMR, Northern East, North Thailand) does have a highly significant spatial clustering.\n\nTherefore, it is recommended for these measures to take place based on the insights :\n\n### Accident Frequency\n\n**Short term:** It would be imperative to implement more speed checks, DUI checkpoints and traffic patrols at the densely plotted out points within the 3 regions at the Clarks Evans plots especially in the months of January, April and December. This is to counter the spike in accident numbers due to the increased vehicle numbers on the road due to their main holiday periods. It will be a temporary measure to allow time to plan and deploy the long term solutions.\n\n**Long term :** If the accident distribution in the Bangkok area is persistently high within Thailand then it suggests that regardless of the reason whether it is due to high traffic volume, poorly maintained roads or lack of traffic safety enforcement a targeted investigation on the root problem is required. After which interventions like road re-designing or traffic law enforcement are necessary to ensure safety in the future.\n\n### Accident Severity\n\n**Short term :** There will be a need for the Transport authority within Thailand to go on high alert and prioritize the emergency-response ability within the North and North Eastern provinces/districts during January and December, with more emphasis in the Northern Eastern Thailand due to the fact that the accident areas within NE Thailand is less clustered and more spread out thus increasing the risks. This will be to allow more efficient and faster emergency responses to the fewer but more severe (with higher risk of death) accidents, instead of focusing on high volume enforcement in Bangkok.\n\n**Long Term :** Suggestion would be to plan, improve and implement better speed-limit enforcement infrastructure, Road-surface maintenance, and roadside safety measures like having more barriers, lighting, signages to help on visibility and safety of the drivers on the road in the rural areas.\n\n# Task 3: Second-Order Point Pattern Analysis\n\nNow, since we had identified that the Bangkok Metropolitan Region, North Eastern Region and North Thailand as the hot-spots for accidents to occur in Thailand, we will screen in to analyse more deeply within this region to get the most impact out of the analysis in preventing future accidents on the road.\n\nFor this Second Order Point Pattern Analysis, we will be utilising the K and L Functions. The reason is as stated below.\n\nClark Evans only looks at a one distance to the nearest point, which computes R and returns a p value for significance at a very short range scale (nearest neighbour distance). However, the K Function and L Function helps to provide a better idea on how clustering varies with distance which the previous Clark-Evans test does not provide.\n\nPreviously we learnt in Thailand Is there clustering at all? Now as a research question we want to understand at which distance does this clustering occur now that we had proven the existance of the clustering at these 3 main regions : Bangkok Metropolitan Region, North Eastern Region and North Thailand.\n\n## K - Function\n\nIn the previous task 2, the Clark-Evans test has established that the accidents does cluster significantly in all 3 highlighted regions, but this is only proven at the nearest neighbour scale. Therefore, for the second order analysis the Ripley's K Function is conducted to get an understanding on the clustering across the full range of spatial scales. Specifically (even though there is also the F and G Function), the K function allows every distance of clustering to be captured to the rmax so every event (denoted as accident in this scenario) up to the rmax can be measured, which helps to identify the spatial scales where the accident is concentrating which is what is required for the objective of the exercise which is to better plan for road safety.\n\n### Considerations & Assumptions made\n\n#### Rmax Consideration for K function calculation\n\nBefore the K function is calculated, we look at the rmax parameter. This is the parameter that sets the maximum inter-point distance at which Ripley's K is evaluated, and is important to evaluate because Ripley's edge correction would be unstable as the evaluation distance grows which is the case for our study where we are looking at large regions within Thailand.\n\nUsually, the default rmax is already derived from the bounding rectangle of the window so the code chunk below is not necessary. However for our scenario, it is necessary to compute the estimated rmax parameters since our dataset has a multipolygon which does overstate the region effective extent. This is for more accurate results and faster computation within R studio. The computed distances below represent the upper bound where K can be reliably interpreted for each of the regions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# For each region, look at the window's extent in km\nrmax_rule <- function(ppp) {\n  W <- Window(ppp)\n  x_extent <- diff(W$xrange)   # in km\n  y_extent <- diff(W$yrange)   # in km\n  rmax <- min(x_extent, y_extent) / 4\n  c(x_extent = x_extent, y_extent = y_extent, rmax = rmax)\n}\n\nrmax_rule(acc_bmr_ppp.km)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n x_extent  y_extent      rmax \n124.84196  94.33823  23.58456 \n```\n\n\n:::\n\n```{.r .cell-code}\nrmax_rule(acc_north_ppp.km)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n x_extent  y_extent      rmax \n422.75425 365.13956  91.28489 \n```\n\n\n:::\n\n```{.r .cell-code}\nrmax_rule(acc_ne_ppp.km)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nx_extent y_extent     rmax \n513.7973 484.8929 121.2232 \n```\n\n\n:::\n:::\n\n\nTherefore the rmax values for bmr, North Thailand and Northern East Thailand is rounded to be 23.58km, 91.37km and 121.33km respectively.\n\n#### Simplification of ppp\n\nAs mentioned in the previous step when creating the ppp in Task 2, the current Thailand boundaries are defined using very detailed polygons with many vertices in the boundary rings. So the OWIN is simplified to ensure that the computation is properly reduced. The analytical results below will not be changed.\n\n### Limitations/Caveats\n\n#### Reduction of nrval and subsampling in specified regions\n\nThe Bangkok Metropolitian region analysis will uses the standard `nrval` (100) and subsampling (1000) values , which is well-suited to the renrvallatively compact BMR window of `rmax` =23.58km. However, the Northern and North-Eastern regions with larger, more elongated boundary windows that are bounded by more complex administrative boundaries, the isotropised correction would be computationally complex to run within R studio with the standard `nrval` and subsampling definitions. Therefore as a counter the the `nrval` for the Northern and North Eastern regions are reduced to 50 and subsampling is reduced to 500.\n\n#### Duplicated Coordinates\n\nAs mentioned in Task 1, there are multiple accidents that has occurred at the same location. However, Ripley's K assumes events are independent, so the multiple accidents ;exact duplicates violate this assumption by artificially inflating short-range clustering. The duplicates were retained because each record represents a genuinely distinct accident, but the resulting K-curve at very short distances (below \\~1 km) should be interpreted with this limitation in mind.\n\n#### Biasedness in Ripley Correction\n\nRipley's isotropised edge correction is used throughout. For irregular windows in this context, the isotropised correction has known bias at larger distances as the search circle extends further beyond the boundary. The `rmax` bound limits this, but some residual bias may persist near the upper end of the evaluation range.\n\n### Bangkok Metropolitan Region\n\nFirst, the set seed is added in to ensure that the points stay the same in every calculation for easier analysis. Then we use the rescaled ppp variables to be put into the Ripley correction to get the best values before we do out the K Function plot for the Bangkok Metropolitan Region.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nacc_bmr_small <- acc_bmr_ppp.km[sample(npoints(acc_bmr_ppp.km), 1000)]\nK_bmr <- Kest(acc_bmr_small, correction = \"Ripley\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(K_bmr, . -r ~ r, ylab= \"K(d)-r\", xlab = \"d(m)\")\n```\n\n::: {.cell-output-display}\n![](Take-Home_ex01_files/figure-html/unnamed-chunk-36-1.png){width=672}\n:::\n:::\n\n\n::: callout-note\nAnalysis :\n\nThe edge-corrected `K̂_iso(r) − r` for the Bangkok Metropolitan Region accidents are plotted against the theoretical CSR expectation (red dashed line). The observed edge corrected curve lies consistently above the CSR line with a widening gap up to `rmax = 23.58 km`, which shows a clustering of accidents rather than spatial randomness that is consistent with the Clark-Evans result (R = 0.265, p \\< 2.2 × 10⁻¹⁶), which identified strong nearest-neighbour clustering.\n\nFormal significance of the deviation across all distances is assessed in the next section using a global envelope test.\n:::\n\nNow we will have to conduct the Complete Spatial Randomness Test to confirm the observed spatial patterns above. To do this, a hypothesis test will be conducted, The hypothesis test will be put under a 5% envelope where p\\<0.05 for the results to be statistically significant (nsim =39 with this setting).\n\nHo = The distribution of accidents at the Bangkok Metropolitan Region are randomly distributed.\n\nH1= The distribution of accidents at the Bangkok Metropolitan Region are not randomly distributed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#A 5% global CSR envelope (nsim = 39, rank = 1), evaluated at 100 distances up to rmax = 23.5 km.\nK_bmr.csr <- envelope(acc_bmr_small, Kest,\n                      nsim = 39, rank = 1, global = FALSE,\n                      rmax = 23.5, nrval = 100)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerating 39 simulated realisations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, \n39.\n\nDone.\n```\n\n\n:::\n:::\n\n\nNow we conduct the final plotting\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(K_bmr.csr, . - r ~ r, xlab=\"d\", ylab=\"K(d)-r\")\n```\n\n::: {.cell-output-display}\n![](Take-Home_ex01_files/figure-html/unnamed-chunk-38-1.png){width=672}\n:::\n:::\n\n\n::: callout-note\nAnalysis :\n\nThe observed curve `K̂_obs(r) − r` lies above the upper envelope (grey area) of the 39 simulated CSR patterns at all distances up to `rmax = 23.58 km`, and the gap widens with increasing `d`.\n\nThis confirms that the accidents in the Bangkok Metropolitan Region does exhibit statistically significant spatial clustering beyond what complete spatial randomness would produce which again is consistent with the Clark-Evans test (R = 0.265, p \\< 2.2 × 10⁻¹⁶), which identified strong nearest-neighbour clustering.\n\nTogether, the two tests have proven that the accidents in the Bangkok Metropolitan Region are not uniformly distributed but concentrate along a spatial structure which most plausibly the urban road network from the Bangkok subregion plot where there are highly intensive highlighted regions on the highways of Bangkok.\n:::\n\n### North Thailand\n\nFirst, the set seed is added in to ensure that the points stay the same in every calculation for easier analysis. Then we use the rescaled ppp variables to be put into the Ripley correction to get the best values before we do out the K Function plot for the Bangkok Metropolitan Region.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nacc_north_small <- acc_north_ppp.km[sample(npoints(acc_north_ppp.km), 500)]\nK_north <- Kest(acc_north_small, correction = \"Ripley\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(K_north, . -r ~ r, ylab= \"K(d)-r\", xlab = \"d(m)\")\n```\n\n::: {.cell-output-display}\n![](Take-Home_ex01_files/figure-html/unnamed-chunk-40-1.png){width=672}\n:::\n:::\n\n\n::: callout-note\nAnalysis :\n\nThe edge-corrected `K̂_iso(r) − r` for the North Thailand Region accidents are plotted against the theoretical CSR expectation (red dashed line). The observed edge corrected curve lies consistently above the CSR line with a widening gap up to `rmax = 91.37 km`, which shows a clustering of accidents rather than spatial randomness that is consistent with the Clark-Evans result (R = 0.3014, p \\< 2.2 × 10⁻¹⁶), which identified strong nearest-neighbour clustering.\n\nFormal significance of the deviation across all distances is assessed in the next section using a global envelope test.\n:::\n\nNow we will have to conduct the Complete Spatial Randomness Test to confirm the observed spatial patterns above. To do this, a hypothesis test will be conducted, The hypothesis and test are as follows:\n\nHo = The distribution of accidents at the Northern Thailand Region are randomly distributed.\n\nH1= The distribution of accidents at the Northern Thailand Region are not randomly distributed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#A 5% global CSR envelope (nsim = 39, rank = 1), evaluated at 50 distances up to rmax = 91.37 km.\nK_north.csr <- envelope(acc_north_small, Kest,\n                      nsim = 39, rank = 1, global = FALSE,\n                      rmax = 91.37, nrval = 50)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerating 39 simulated realisations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, \n39.\n\nDone.\n```\n\n\n:::\n:::\n\n\nNow we conduct the final plotting\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(K_north.csr, . - r ~ r, xlab=\"d\", ylab=\"K(d)-r\")\n```\n\n::: {.cell-output-display}\n![](Take-Home_ex01_files/figure-html/unnamed-chunk-42-1.png){width=672}\n:::\n:::\n\n\n::: callout-note\nAnalysis :\n\nSimilar to the Bangkok Metropolitan region, the observed curve `K̂_obs(r) − r` lies above the upper envelope (grey area) of the 39 simulated CSR patterns at all distances up to `rmax = 91.37 km`, and the gap widens with increasing `d`.\n\nThis again confirms that the accidents in the Northern Thailand Region does exhibit statistically significant spatial clustering beyond what complete spatial randomness would produce which again is consistent with the Clark-Evans test (R = 0.3014 , p \\< 2.2 × 10⁻¹⁶), which identified strong nearest-neighbour clustering.\n\nTogether, the two tests have proven that the accidents in the North Thailand Region are not uniformly distributed but concentrate along the spatial structure which is clustered more towards the bottom area of North Thailand.\n:::\n\n### Northern East Thailand\n\nFirst, the set seed is added in to ensure that the points stay the same in every calculation for easier analysis. Then we use the rescaled ppp variables to be put into the Ripley correction to get the best values before we do out the K Function plot for the Northern East Region.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nacc_ne_small <- acc_ne_ppp.km[sample(npoints(acc_ne_ppp.km), 500)]\nK_ne <- Kest(acc_ne_small, correction = \"Ripley\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(K_ne, . -r ~ r, ylab= \"K(d)-r\", xlab = \"d(m)\")\n```\n\n::: {.cell-output-display}\n![](Take-Home_ex01_files/figure-html/unnamed-chunk-44-1.png){width=672}\n:::\n:::\n\n\n::: callout-note\nAnalysis :\n\nThe edge-corrected `K̂_iso(r) − r` for the North Eastern Thailand Region accidents are plotted against the theoretical CSR expectation (red dashed line). The observed edge corrected curve lies consistently above the CSR line with a widening gap up to `rmax = 121.33 km`, which shows a clustering of accidents rather than spatial randomness that is consistent with the Clark-Evans result (R = 0.3014, p \\< 2.2 × 10⁻¹⁶), which identified strong nearest-neighbour clustering. However it is to note that as compared to the other 2 regions, the distance between the edge Corrected line is close to the CSR expectation which suggest that the clustering here in North East Thailand is not as strong as that of the other 2 regions.\n\nFormal significance of the deviation across all distances is assessed in the next section using a global envelope test.\n:::\n\nNow we will have to conduct the Complete Spatial Randomness Test to confirm the observed spatial patterns above. To do this, a hypothesis test will be conducted, The hypothesis and test are as follows:\n\nHo = The distribution of accidents at the Northern East Region are randomly distributed.\n\nH1= The distribution of accidents at the Northern East Region are not randomly distributed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#A 5% global CSR envelope (nsim = 39, rank = 1), evaluated at 50 distances up to rmax = 121.33 km.\nK_ne.csr <- envelope(acc_ne_small, Kest,\n                        nsim = 39, rank = 1, global = FALSE,\n                        rmax = 121.33, nrval = 50)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerating 39 simulated realisations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, \n39.\n\nDone.\n```\n\n\n:::\n:::\n\n\nNow we conduct the final plotting\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(K_ne.csr, . - r ~ r, xlab=\"d\", ylab=\"K(d)-r\")\n```\n\n::: {.cell-output-display}\n![](Take-Home_ex01_files/figure-html/unnamed-chunk-46-1.png){width=672}\n:::\n:::\n\n\n::: callout-note\nAnalysis :\n\nThe observed K-curve lies above the upper 5% CSR envelope at all distances above approximately 5km and the gap again widens progressively up to `rmax = 121.33 km`.\n\nThis confirms statistically significant spatial clustering of accidents in North-Eastern Thailand, consistent with the Clark-Evans result (R = 0.419, p \\< 2.2 × 10⁻¹⁶). However as mentioned before, the magnitude of the deviation is proven again to be smaller than for the Bangkok Metropolitan region and Northern Thailand. The pattern is however qualitatively the same, where the accidents are more spread out across the North Eastern region, but is concentrated along the region's road network rather than randomly distributed. The narrow grey envelope reflects the high statistical power of the test at n = 1000, so even modest deviations from CSR are detectable.\n:::\n\nK-Function plots can be paired together with L-function plots for analysis. However since in overall the K Function plot curve shows obvious deviations from the CSR, there is no need to look at the L function which is the monotone transformation of the K function itself, where this step is redundant in our scenario. Hence we will now move forward to do the integration and interpretation from everything so far.\n\n# Task 4 : Integration & Interpretation\n\n## Overview\n\nThe first-order and second-order analyses conducted in Tasks 2 and 3 examine the same accident datasets with two fundamentally different perspectives.\n\nThe first-order analysis involves a point pattern recognition, looking at where and when is the accident intensity the highest where the point pattern is treated as a realisation of a spatially and temporally varying intensity surface.\n\nThe second-order analysis instead looks if events interact with one another and at which distance, treating the point pattern as a realisation of a spatial interaction process.\n\nNeither view alone is sufficient to characterise the accident pattern in Thailand; together, however, they provide a coherent and mutually validating picture, which will be integrated and interpreted in this section where the first order analysis will localise the pattern and the second order will characterise it.\n\n## Combined Insights\n\n### Location\n\nFrom the first order STKDE, the Bangkok Metropolitan region is a dominant hotspot for accidents where the North and North east regions of Thailand have higher fatality accident rates. This is complemented with the K Function which confirms all accidents within the highlighted regions are clustered at every distance scale with the Bangkok region having the highest magnitude of clustering amongst the 3 regions from the Clark-Evans analysis. This therefore does confirm that the Bangkok Metropolitan region is a genuine multi-scale cluster which cannot be a fact confirmed alone. It also proves that both orders of analysis are highly consistent with each other where strength of clustering and direction are agreed upon across the highlighted regions.\n\nIt is to note however, that there is the possibility that some rural accidents are not reported due to the delayed rescue services even though in the assumptions of the exercise we assumed that the data collected is the true representative of Thailand's accidents in 2022.\n\n### Seasonality\n\nIt is known that April and December are the peak timings when the accidents frequency is the highest in Thailand which is likely due these months being the [primary holiday periods](https://blogs.worldbank.org/en/eastasiapacific/thailand-road-safety-will-never-happen-accident) (Chanin,2014) in the country. January and December instead shows a shocking high fatality as compared to the other months. To note, from here it is shown that the fatality STKDE does diverge from the overall STKDE, which shows that the frequency and severity of accidents have to be considered as different spatial processes. From the K function, the spatial clusters are identified within the 3 regions of Thailand, on which highways are more at risk for accidents to occur. With these information combined, it helps the government to identify the holiday period risk zones, at and when to focus efforts to reduce the accident fatalities with greatest impacts.\n\n### Severity\n\nThe first order STKDE shows that the rural North Thailand and North Eastern region has greater fatality numbers, though the K function is weaker amongst the 3 regions though still being significant. Therefore, when combining the information, it shows that the rural fatal accidents are actually more dispersed but are still non-random from the still present clustering proven. This suggests that the government can still rely on the clustering trends to concentrate efforts on to reduce accident rates but more resources are required.\n\nThe Severity or fatality rates in the rural North Thailand and North Eastern region may be higher because of the longer emergency response timings of the emergency services. With common fact that hospitals with advanced medical equipment and resources are usually less accessible in rural areas, more time is required for the person to get emergency help where victims of the accidents in these rural areas may die before reaching the hospital or miss the golden window for treatment. Hence it is possible that some deaths in the rural accidents may not be severe as some of the accidents in the urban areas that has a higher chance to save the accident victims.\n\nFurthermore, the North Eastern region accidents may be more dispersed due to the lower population density within the region, since North Eastern contains the most provinces within Thailand. Hence clustering may look more dispersed.\n\n## Assumptions and limitations\n\nAs mentioned in task 1, there are assumptions made for the exercise due since there are many layers of factors in reality that is difficult to apply in any type of analysis. It is now explained in detail below.\n\n### Independence of events\n\nWe do have to note that it is assumed in this exercise that the accidents are independent. However due to the [chaotic road conditions and lack of road safety enforcement](https://asirt-member-rsrs.s3.amazonaws.com/ASIRT-Thailand-RSR.pdf) (ASIRT,2023) , reality shows that there is the presence of multi vehicle crashes and therefore duplicate coordinates. So it has to be noted of the inflation of clustering signals in both the Clark-Evans and K Function calculations and therefore an upper bound on the clustering strength.\n\n### Homogeneity\n\nIt is assumed on the uniformed risk of accident frequency and fatality across Thailand, but as mentioned the traffic volume and quality can vary in different parts of the country with notably differences between urban and rural roads. Therefore we have to note that the clustering shown in the analysis may have the possibility of reflecting population density variation rather than pure interactions.\n\n### Isotropy\n\nThe road Networks are linear, but we are assuming that the KDE and K function have the isotropic spread, where the true clustering is through 1D networks rather than a 2D space. Therefore the clustering may be overestimated by a small extent in short distances since the points on the same roads are artificially close in 2D coordinates.\n\n### Sampling & Edge effects\n\nIn task 3, due to the computation being too high for the code to run proper, sampling is applied to the Bangkok region (1000 subsamples) and the North with North Eastern region (500 subsamples each) which may have the impact of losing a little fine-scale clustering signals. The Ripley correction would also help but the indentity of the multi-polygon windows within the dataset itself would have some imperfections in the edge correction. The Simplification of the OWIN in task 2 also may introduce a little minor boundary distortions though it is still possible to gain major insights.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Recompute STKDE with different spatial bandwidths\nh_values <- c(20000, 30000, 38160, 50000, 70000)  # 20, 30, 38 (default), 50, 70 km\n\nst_kde_list <- lapply(h_values, function(h) {\n  spattemp.density(acc_month_owin, h = h)\n})\n\n# ---- Plot April (month 4, the peak month) at each bandwidth ----\npar(mfrow = c(1, 5))\nfor (i in seq_along(h_values)) {\n  plot(st_kde_list[[i]], 4,\n       override.par = FALSE,\n       fix.range = TRUE,\n       main = paste0(\"h = \", h_values[i] / 1000, \" km\"))\n}\n```\n\n::: {.cell-output-display}\n![](Take-Home_ex01_files/figure-html/unnamed-chunk-47-1.png){width=672}\n:::\n:::\n\n\nWith the different STKDEs computed, it shows that the Bangkok Metropolitan Region remains the dominant hotspot at every bandwidth and confirms that the primary conclusion is robust to bandwidth selection. However the colour intensity differs across the plots since the larger bandwidths will smooth the density over a wider area so in overall the identification of secondary clusters is bandwidth-sensitive but the primary hotspot is not which suggests that within our analysis the peak locations and primary region analysis are reliable.\n\n# Task 5 : Geovisualisation and Analytical Interpretation\n\n## Vehicle Profile by Region\n\nSince we have the geospatial analysis insights, it is imperative to support it by looking into detail what type of accident has occurred in Thailand in the chosen 3 regions to allow the government to provide better solutions to mitigate accident frequency and severity.\n\nTherefore first it is required to check for the vehicle types and re-group if necessary.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Check unique vehicle types and their frequencies\nacc %>%\n  st_drop_geometry() %>%\n  count(vehicle_type, sort = TRUE) %>%\n  print(n = 30)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 15 × 2\n   vehicle_type                     n\n   <chr>                        <int>\n 1 4-wheel pickup truck          7722\n 2 private/passenger car         5240\n 3 motorcycle                    3175\n 4 large truck with trailer      1712\n 5 other                          926\n 6 6-wheel truck                  817\n 7 7-10-wheel truck               625\n 8 van                            235\n 9 large passenger vehicle        101\n10 passenger pickup truck          86\n11 motorized tricycle              73\n12 bicycle                         42\n13 pedestrian                      39\n14 tractor/agricultural vehicle    17\n15 three-wheeled vehicle            7\n```\n\n\n:::\n:::\n\n\nThere are 15 groups in total which may be too granular to give proper insights so we will create 5 groups based on what is available : Pickup, cars, motorcycle, truck and others\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacc <- acc %>%\n  mutate(\n    vehicle_grp = case_when(\n      vehicle_type %in% c(\"4-wheel pickup truck\",\n                          \"passenger pickup truck\") ~ \"Pickup\",\n      vehicle_type %in% c(\"private/passenger car\",\n                          \"van\") ~ \"Car\",\n      vehicle_type %in% c(\"motorcycle\",\n                          \"motorized tricycle\",\n                          \"three-wheeled vehicle\") ~ \"Motorcycle\",\n      vehicle_type %in% c(\"large truck with trailer\",\n                          \"6-wheel truck\",\n                          \"7-10-wheel truck\",\n                          \"tractor/agricultural vehicle\") ~ \"Truck\",\n      TRUE ~ \"Other\"   # other, large passenger vehicle, bicycle, pedestrian\n    )\n  )\n\n# Verify the grouping\nacc %>%\n  st_drop_geometry() %>%\n  count(vehicle_grp, sort = TRUE) %>%\n  mutate(pct = round(100 * n / sum(n), 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 3\n  vehicle_grp     n   pct\n  <chr>       <int> <dbl>\n1 Pickup       7808  37.5\n2 Car          5475  26.3\n3 Motorcycle   3255  15.6\n4 Truck        3171  15.2\n5 Other        1108   5.3\n```\n\n\n:::\n:::\n\n\nWe also need to aggregate the regions into the original datasets, which will be a simple link since we had defined the region boundaries through a previous task\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Remove the \" Province\" suffix from all three vectors\nbmr_provinces       <- str_remove(bmr_provinces,       \" Province$\")\nnorth_provinces     <- str_remove(north_provinces,     \" Province$\")\nnortheast_provinces <- str_remove(northeast_provinces, \" Province$\")\n\n# Check they now match\nprint(north_provinces)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Chiang Mai\"   \"Chiang Rai\"   \"Lampang\"      \"Lamphun\"      \"Mae Hong Son\"\n[6] \"Nan\"          \"Phayao\"       \"Phrae\"        \"Uttaradit\"   \n```\n\n\n:::\n\n```{.r .cell-code}\n# Re-run the region assignment\nacc <- acc %>%\n  mutate(\n    region = case_when(\n      province_en %in% bmr_provinces       ~ \"BMR\",\n      province_en %in% north_provinces     ~ \"North\",\n      province_en %in% northeast_provinces ~ \"North-East\",\n      TRUE ~ \"Other\"\n    ),\n    region = factor(region, levels = c(\"BMR\", \"North\", \"North-East\", \"Other\"))\n  )\n\nacc %>% st_drop_geometry() %>% count(region, sort = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 2\n  region         n\n  <fct>      <int>\n1 Other      10834\n2 North-East  3809\n3 BMR         3591\n4 North       2583\n```\n\n\n:::\n:::\n\n\nNow with the groupings done we look into creating the actual visuals\n\n### Accident Frequency\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(acc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 6 features and 19 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 420327.5 ymin: 877127.7 xmax: 935504.6 ymax: 1924811\nProjected CRS: WGS 84 / UTM zone 47N\n# A tibble: 6 × 20\n  acc_code incident_datetime   report_datetime     province_en            agency\n     <dbl> <dttm>              <dttm>              <chr>                  <chr> \n1  6566872 2022-01-01 00:01:00 2022-01-02 11:45:00 Chai Nat               depar…\n2  6566880 2022-01-01 00:01:00 2022-01-02 11:44:00 Maha Sarakham          depar…\n3  5706553 2022-01-01 00:03:00 2022-02-09 08:41:00 Chumphon               depar…\n4  5485750 2022-01-01 00:05:00 2022-01-02 06:21:00 Phuket                 depar…\n5  5624452 2022-01-01 00:05:00 2022-01-24 09:59:00 Udon Thani             depar…\n6  6566842 2022-01-01 00:05:00 2022-01-02 11:46:00 Phra Nakhon Si Ayutth… depar…\n# ℹ 15 more variables: vehicle_type <chr>, presumed_cause <chr>,\n#   accident_type <chr>, number_of_vehicles_involved <dbl>,\n#   number_of_fatalities <dbl>, number_of_injuries <dbl>,\n#   weather_condition <chr>, road_description <chr>, slope_description <chr>,\n#   geometry <POINT [m]>, DayofYear <dbl>, Month_num <dbl>, Month_fac <ord>,\n#   vehicle_grp <chr>, region <fct>\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Aggregation of original dataset to create visualisation \nveh_region <- acc %>%\n  filter(region != \"Other\") %>%\n  st_drop_geometry() %>%\n  count(region, vehicle_grp, name = \"n\") %>%\n  group_by(region) %>%\n  mutate(pct = 100 * n / sum(n)) %>%\n  ungroup()\n\nveh_region\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 15 × 4\n   region     vehicle_grp     n   pct\n   <fct>      <chr>       <int> <dbl>\n 1 BMR        Car          1221 34.0 \n 2 BMR        Motorcycle    405 11.3 \n 3 BMR        Other         419 11.7 \n 4 BMR        Pickup       1030 28.7 \n 5 BMR        Truck         516 14.4 \n 6 North      Car           681 26.4 \n 7 North      Motorcycle    569 22.0 \n 8 North      Other          60  2.32\n 9 North      Pickup       1006 38.9 \n10 North      Truck         267 10.3 \n11 North-East Car           979 25.7 \n12 North-East Motorcycle    512 13.4 \n13 North-East Other         206  5.41\n14 North-East Pickup       1567 41.1 \n15 North-East Truck         545 14.3 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Plot\nggplot(veh_region,\n       aes(x = vehicle_grp, y = pct, fill = region)) +\n  geom_col(position = position_dodge(width = 0.8), width = 0.7) +\n  geom_text(aes(label = round(pct, 1)),\n            position = position_dodge(width = 0.8),\n            vjust = -0.4, size = 3) +\n  scale_fill_manual(values = c(\"BMR\"        = \"#d73027\",\n                               \"North\"      = \"#4575b4\",\n                               \"North-East\" = \"#fdae61\")) +\n  labs(\n    title = \"Vehicle Distribution (Accident Frequency)\",\n    subtitle = \"Thailand 2022 accidents within highlighted region\",\n    x = NULL,\n    y = \"Percentage of accidents (%)\",\n    fill = \"Region\"\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(\n    legend.position = \"top\",\n    panel.grid.major.x = element_blank()\n  )\n```\n\n::: {.cell-output-display}\n![](Take-Home_ex01_files/figure-html/unnamed-chunk-52-1.png){width=672}\n:::\n:::\n\n\n::: callout-note\n**Analysis : vehicle-type composition of all recorded accidents in the BMR, Northern, and North-Eastern regions.**\n\nPassenger cars dominate in the Bangkok region (34.0%) while pickup only accounts for 28.7%. However in Northern and North-Eastern Thailand, the pattern reverses where pickups are the leading vehicle type (38.9% and 41.1% respectively), with cars falling to approximately 26%. Motorcycles amongst all vehicle types show the greatest relative divergence where the North having 22% of accidents with motorcycles as compared to the other 2 regions (11.3% & 13.4%).\n\nThis suggests that the vehicle mix in rural accidents is skewed towards vehicles associated with higher fatality risk (pickups carrying passengers in open beds, and motorcycles), which may contributes to the elevated rural fatality burden identified in Task 2. This will be confirmed again in the next subsection : accident fatalities.\n\n**Caveat:** The vehicle type is recorded per accident, not per casualty, so multi-vehicle crashes may under-represent secondary vehicles. Differences in reporting rates between urban and rural areas may also affect the comparison.\n:::\n\n### Accident Fatalities\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Aggregation of original dataset to create visualisation \nveh_region_fatal <- acc %>%\n  filter(region != \"Other\", number_of_fatalities > 0) %>%\n  st_drop_geometry() %>%\n  count(region, vehicle_grp, name = \"n\") %>%\n  group_by(region) %>%\n  mutate(pct = 100 * n / sum(n)) %>%\n  ungroup()\n\nveh_region_fatal\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 15 × 4\n   region     vehicle_grp     n   pct\n   <fct>      <chr>       <int> <dbl>\n 1 BMR        Car            28 17.6 \n 2 BMR        Motorcycle     80 50.3 \n 3 BMR        Other           2  1.26\n 4 BMR        Pickup         23 14.5 \n 5 BMR        Truck          26 16.4 \n 6 North      Car            39 16.2 \n 7 North      Motorcycle    122 50.8 \n 8 North      Other           4  1.67\n 9 North      Pickup         59 24.6 \n10 North      Truck          16  6.67\n11 North-East Car           119 20.8 \n12 North-East Motorcycle    259 45.3 \n13 North-East Other          22  3.85\n14 North-East Pickup        123 21.5 \n15 North-East Truck          49  8.57\n```\n\n\n:::\n\n```{.r .cell-code}\n# Plot\nggplot(veh_region_fatal,\n       aes(x = vehicle_grp, y = pct, fill = region)) +\n  geom_col(position = position_dodge(width = 0.8), width = 0.7) +\n  geom_text(aes(label = round(pct, 1)),\n            position = position_dodge(width = 0.8),\n            vjust = -0.4, size = 3) +\n  scale_fill_manual(values = c(\"BMR\"        = \"#d73027\",\n                               \"North\"      = \"#4575b4\",\n                               \"North-East\" = \"#fdae61\")) +\n  labs(\n    title = \"Vehicle Distribution (Accident Fatalities)\",\n    subtitle = \"Thailand 2022 fatal accidents within highlighted regions\",\n    x = NULL,\n    y = \"Percentage of fatal accidents (%)\",\n    fill = \"Region\"\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(\n    legend.position = \"top\",\n    panel.grid.major.x = element_blank()\n  )\n```\n\n::: {.cell-output-display}\n![](Take-Home_ex01_files/figure-html/unnamed-chunk-53-1.png){width=672}\n:::\n:::\n\n\n::: callout-note\n**Analysis** **:** **vehicle-type composition of fatal accidents in the BMR, Northern, and North-Eastern regions of Thailand in 2022**\n\nIt is clear that the motorcycles dominate being the cause of fatal accidents in all three regions, accounting for 50.3% in the BMR, 50.8% in the North, and 45.3% in North-Eastern Thailand. Conversely, pickups and cars see their shares drop sharply — pickups fall from around 40% of accidents to an average of 20% of fatalities, while cars fall from around 30% to 16-21%. This shows that overall motorcyclists are at greatest risk of dying when being in an accident so measures should be put in place for them if Thailand wants to see a drop in fatalities.\n\n**Caveat:** The fatal subsample is smaller (Total of = 2,273 fatalities), so regional percentages carry wider confidence intervals.\n:::\n\n## Accident Causes\n\nTo be able to solve a problem the root cause must be identified. Therefore it is necessary to approach this exercise with the same concept : The main causes for the accidents to occur in Thailand is essential to be known if public safety can be achieved.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacc %>%\n  st_drop_geometry() %>%\n  count(presumed_cause, sort = TRUE) %>%\n  print(n = 50)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 49 × 2\n   presumed_cause                                      n\n   <chr>                                           <int>\n 1 speeding                                        15296\n 2 cutting in closely by people/vehicles/animals    1538\n 3 falling asleep                                   1269\n 4 vehicle equipment failure                         564\n 5 other                                             555\n 6 driving under the influence of alcohol            293\n 7 running red lights/traffic signals                232\n 8 unfamiliarity with the route/unskilled driving    161\n 9 worn-out/tire blowout                             112\n10 illegal overtaking                                 99\n11 debris/obstruction on the road                     82\n12 overloaded vehicle                                 61\n13 slippery road                                      61\n14 loss of control                                    49\n15 failure to yield/signal                            46\n16 brake/anti-lock brake system failure               43\n17 reversing vehicle                                  41\n18 tailgating                                         40\n19 failure to yield right of way                      39\n20 abrupt lane change                                 38\n21 dangerous curve                                    28\n22 insufficient light                                 26\n23 ignoring stop sign while leaving intersection      22\n24 using mobile phone while driving                   21\n25 aggressive driving/overtaking                      12\n26 medical condition                                  11\n27 inadequate visibility                              10\n28 sudden stop                                        10\n29 failure to signal enter/exit parking                8\n30 vehicle electrical system failure                   7\n31 disabled vehicle without proper signals             6\n32 straddling lanes                                    6\n33 driving without headlights/illumination             4\n34 no presumed cause related to road conditions        4\n35 repair/construction on the road                     4\n36 road in poor condition                              4\n37 driving in the wrong lane                           2\n38 external disturbance                                2\n39 internal disturbance                                1\n40 narrow road                                         1\n41 no presumed cause related to driver                 1\n42 no presumed cause related to vehicle conditions     1\n43 no road divider lines                               1\n44 no traffic light system                             1\n45 no traffic signs                                    1\n46 obstruction in sight                                1\n47 turn signal system failure                          1\n48 using psychoactive substances                       1\n49 มึนเมาจากแอลกอฮอล์                                    1\n```\n\n\n:::\n:::\n\n\n::: callout-note\nมึนเมาจากแอลกอฮอล์ after translation is drunk from alcohol.\n:::\n\nSo it is best to regroup the accident causes so that a good analysis can be done. The groupings will be decided as such :\n\n- speeding since it as the greatest numbers of 15296 amongst all other groups and has to be a standalone.\n\n- Reckless Driving: Known to be deliberate and unsafe manoeuvres on the road, which will be an interesting cause to be studies within the urbans areas.\n\n- Driver state/Fatigue : Known to be driver-state issues, which is a psychological type of group that is separate from the deliberate risk-takers and is hence worth studying on its own.\n\n- Vehicle Failure : Mechnical issues, it is also worth knowing to see if imposes on vehicle maintenance or scrapping is required.\n\n- Alcohol/Drugs : it is an important standalone cause that is enforceable and well-studied, it is also difficult to lump this category therefore under others or any other groups\n\n- Environmental: Accidents can occur due to mother nature which may an influence worth noting in Thailand\n\n- Others\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacc <- acc %>%\n  mutate(\n    cause_grp = case_when(\n      \n      # Speeding \n      str_detect(presumed_cause,\n                 regex(\"^speeding$\", ignore_case = TRUE)) ~ \"Speeding\",\n      \n      # Alcohol/Drugs\n      str_detect(presumed_cause,\n                 regex(\"alcohol|psychoactive|มึนเมา\",\n                       ignore_case = TRUE)) ~ \"Alcohol / Drugs\",\n      \n      # Fatigue\n      str_detect(presumed_cause,\n                 regex(\"falling asleep|fatigue|drowsy|medical condition|mobile phone\",\n                       ignore_case = TRUE)) ~ \"Fatigue\",\n      \n      # Reckless Driving\n      str_detect(presumed_cause,\n                 regex(\"cutting in|illegal overtaking|aggressive|loss of control|tailgat|abrupt lane|sudden stop|straddling|reversing|running red light|ignore.*stop|failure to yield|wrong lane|without headlights|failure to signal|unfamiliar\",\n                       ignore_case = TRUE)) ~ \"Reckless Driving\",\n      \n      # Vehicle Failure\n      str_detect(presumed_cause,\n                 regex(\"equipment failure|tire|tyre|brake|electrical|turn signal|overloaded|disabled vehicle\",\n                       ignore_case = TRUE)) ~ \"Vehicle Failure\",\n      \n      # Environmental \n      str_detect(presumed_cause,\n                 regex(\"debris|slippery|dangerous curve|insufficient light|visibility|road.*condition|construction|narrow|divider|traffic light|traffic sign|obstruction|repair|external disturbance|internal disturbance|no presumed cause\",\n                       ignore_case = TRUE)) ~ \"Environmental\",\n      \n      # Others \n      TRUE ~ \"Others\"\n    ),\n    \n    cause_grp = factor(cause_grp, levels = c(\n      \"Speeding\", \"Reckless Driving\", \"Fatigue\",\n      \"Vehicle Failure\", \"Alcohol / Drugs\", \"Environmental\", \"Others\"\n    ))\n  )\n\n# To verify the classification in case of errors\nacc %>%\n  st_drop_geometry() %>%\n  count(cause_grp, sort = TRUE) %>%\n  mutate(pct = round(100 * n / sum(n), 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 3\n  cause_grp            n   pct\n  <fct>            <int> <dbl>\n1 Speeding         15296  73.5\n2 Reckless Driving  2325  11.2\n3 Fatigue           1301   6.2\n4 Vehicle Failure    794   3.8\n5 Others             577   2.8\n6 Alcohol / Drugs    295   1.4\n7 Environmental      229   1.1\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacc %>%\n  filter(region != \"Other\") %>%\n  st_drop_geometry() %>%\n  count(region, cause_grp) %>%\n  group_by(region) %>%\n  mutate(pct = round(100 * n / sum(n), 1)) %>%\n  select(region, cause_grp, pct) %>%\n  pivot_wider(names_from = region, values_from = pct) %>%\n  print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 4\n  cause_grp          BMR North `North-East`\n  <fct>            <dbl> <dbl>        <dbl>\n1 Speeding          71.3  78.5         76.7\n2 Reckless Driving   8.4   9.6         10.5\n3 Fatigue            2     5.4          7.5\n4 Vehicle Failure    3.3   2.3          2.8\n5 Alcohol / Drugs    1.1   2.8          1.2\n6 Environmental      0.7   1.1          0.9\n7 Others            13.3   0.3          0.3\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Aggregating values \ncause_region <- acc %>%\n  filter(region != \"Other\") %>%\n  st_drop_geometry() %>%\n  count(region, cause_grp) %>%\n  group_by(region) %>%\n  mutate(pct = round(100 * n / sum(n), 1)) %>%\n  ungroup()\n\n#Plotting heatmap\nggplot(cause_region, aes(x = region, y = cause_grp, fill = pct)) +\n  geom_tile(colour = \"white\", linewidth = 0.8) +\n  geom_text(aes(label = paste0(pct, \"%\")),\n            colour = \"black\", size = 3.8) +\n  scale_fill_stepsn(\n    colors = c(\"#fee5d9\", \"#fcae91\", \"#fb6a4a\", \"#cb181d\", \"#67000d\"),\n    breaks = c(0, 2, 5, 10, 20, 80),\n    name = \"% of accidents\"\n  ) +\n  labs(\n    title = \"Presumed Cause Profile by Region\",\n    subtitle = \"Thailand 2022\",\n    x = NULL, y = NULL\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(\n    panel.grid = element_blank(),\n    axis.text.x = element_text(size = 11),\n    axis.text.y = element_text(size = 11),\n    legend.position = \"right\"\n  )\n```\n\n::: {.cell-output-display}\n![](Take-Home_ex01_files/figure-html/unnamed-chunk-57-1.png){width=672}\n:::\n:::\n\n\n::: callout-note\n**Analysis : Presumed Cause Profile by Region**\n\nSpeeding dominates all three regions (71.3%–78.5%), though variation variation can be seen in smaller causes.\n\nFatigue rises sharply from urban to rural settings with 2.0% of accidents in the Bangkok region, 5.4% in the North, and 7.5% in the North-East, suggesting long rural roads causes more fatigue.\n\nReckless driving is stable across regions (8.4%–10.5%), suggesting it is a universal problem rather than an urban-specific one. Alcohol and drug involvement is surprisingly low with the North highlighted at 2.8% (compared to 1.1% and 1.2%)\n\nNotably, the BMR records 13.3% of accidents as \"Other\" compared to only 0.3% in rural regions — a data-quality discrepancy suggesting BMR cause classification is less reliable.\n\n**Caveat:** The cause of the accident is likely to be deemed through field judgment, rather than a forensic finding and Speeding's dominance may be reflecting recording practice instead the true cause.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Aggregating values\ncause_veh <- acc %>%\n  filter(vehicle_grp != \"Other\", region != \"Other\") %>%\n  st_drop_geometry() %>%\n  count(vehicle_grp, cause_grp) %>%\n  group_by(vehicle_grp) %>%\n  mutate(pct = round(100 * n / sum(n), 1)) %>%\n  ungroup()\n\n# Heatmap\nggplot(cause_veh, aes(x = vehicle_grp, y = cause_grp, fill = pct)) +\n  geom_tile(colour = \"white\", linewidth = 0.8) +\n  geom_text(aes(label = paste0(pct, \"%\")),\n            colour = \"black\", size = 3.8) +\n  scale_fill_gradient(low = \"#fee5d9\", high = \"#a50f15\",\n                      name = \"% within vehicle\") +\n  labs(\n    title = \"Presumed Cause Profile by Vehicle Type\",\n    subtitle = \"Thailand 2022\",\n    x = NULL, y = NULL\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(\n    panel.grid = element_blank(),\n    axis.text.x = element_text(size = 11),\n    axis.text.y = element_text(size = 11),\n    legend.position = \"right\"\n  )\n```\n\n::: {.cell-output-display}\n![](Take-Home_ex01_files/figure-html/unnamed-chunk-58-1.png){width=672}\n:::\n:::\n\n\n::: callout-note\n**Presumed Cause Profile by Vehicle Type**\n\nAgain it is clear that speeding is the cause that dominates all vehicle types as well. However reckless driving is disproportionately recorded for motorcycle accidents (21.8%), compared to 7%–8.8% for all other vehicles. So motorcyclist exhibit more reckless driving behaviours like cutting lanes and illegal overtaking, a common behaviour motorcyclists have during high traffic situations, increasing risk of accidents exponentially.\n\nVehicle failure concentrates in trucks (7.4%), reflecting the mechanical complexity and heavier loads of commercial vehicles, while fatigue is roughly even across cars, pickups, and trucks (5.7%–6.3%) but notably lower for motorcycles (1.5%).\n\nAlcohol/drug involvement is highest for motorcycles (5.8%), which is consistent with the higher risk profile of motorcyclists in Thailand.\n\n**Caveat:** The cause of the accident is likely to be deemed through field judgment, rather than a forensic finding, especially with the careless denoting of the original dataset where มึนเมาจากแอลกอฮอล์ should be directly put into \"alcohol\"\n:::\n\n# Task 6 : Public Safety Planning & Management\n\n## Recap of Analysis findings\n\nThe spatio-temporal kernel density estimates and Clark-Evans tests provide strong evidence that road traffic accidents in Thailand are not randomly distributed, and all three highlighted regions: the Bangkok Metropolitan Region (BMR), Northern Thailand, and North-Eastern Thailand show statistically significant clustering (p \\< 2.2 × 10⁻¹⁶).\n\nBMR has the strongest clustering (R = 0.265) and functions as a constant, accident hotspot. But the Northern and North-Eastern regions has an elevated fatality intensity despite showing dispersed patterns (R = 0.301 and R = 0.419, respectively), especially in January and December.\n\nAccident frequency peaks in April and December, coinciding with the Songkran and New Year holidays. While fatality intensity concentrates in January and December, mainly in rural regions from the temporal analysis.\n\nVehicle-type profiling further shows that motorcycles account for over 45% of fatal accidents across all three regions, with pickup trucks dominating accident frequency in rural areas. Speeding is seen as the main cause in 71–79% of accidents, though it may be a recording practice rather a forensic finding.\n\n## Recommendations & Way Ahead\n\nThe findings will aid resource allocation and emergency response planning.\n\nWith the BMR as a multi-scale, statistically significant cluster, the government can have targeted infrastructure investment into areas like road redesigning, improved signages, and speed-calibration measures at specific highway segments identified in the K-function plots.\n\nWhereas for Northern and North-Eastern Thailand, the elevated rural fatality burden suggests a need for enhanced emergency medical services and faster response times, given the association between rurality, delayed treatment, and higher death rates.\n\nSeasonal peaks (January, April, and December) should be flagged to schedule enforcement campaigns like speed checks, DUI checkpoints, and patrols with more focus on the speed checks like building more automated police cameras to stop speeding since it is a dominating cause of accidents.\n\nMotorcycles being the most common vehicle in fatal accidents, more policies should be enforced for mandatory helmet use, rider training, and infrastructure separation.\n\n## Interpretations requiring additional analysis\n\nIt is determined that fatality intensity is higher in rural areas may likely be due to longer emergency response times. But more analysis is required where hospital locations are needed to look at hospital access, or current road design to have a better understanding on how exactly should the roads be improved for public safety.\n\nRecommendations like vehicle safety inspections also require additional data on traffic volume at peak hours, road conditions, enforcement density, and socio-economic factors for the best decision making.\n\n(395 words)\n",
    "supporting": [
      "Take-Home_ex01_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}